### ISSUE TITLE
Error: systemimage: Error: Error: {error:{killed:false,code:1,signal:null,cmd:C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb

### ISSUE THREAD

**Issue by mem101296** [ubports/ubports-installer#1159]
I'm getting this on Windows and Linux.

![2020-04-03 16_51_59-UBports Installer (0 4 17-beta)](https://user-images.githubusercontent.com/19231888/78385521-99476980-75a1-11ea-8674-a017a393354e.png)

**Comment by mem101296** [comment]
Title: Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}

error: Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}
stack trace: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}
    at C:\Users\mem10\AppData\Local\Temp\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\resources\app.asar\src\system-image.js:84:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
command: adb: {"args":["-P",5037,"shell","mount -a"],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process\r\n"}
debug: adb wiped cache
command: adb: {"args":["-P",5037,"shell","rm","-rf","/cache/*"],"error":null,"stdout":"","stderr":""}
command: adb: {"args":["-P",5037,"shell","cat","/etc/recovery.fstab"],"error":null,"stdout":"# Android fstab file.\r\n# The filesystem that contains the filesystem checker binary (typically /system) cannot\r\n# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK\r\n\r\n#TODO: Add 'check' as fs_mgr_flags with data partition.\r\n# Currently we dont have e2fsck compiled. So fs check would failed.\r\n\r\n#<src>                                                       <mnt_point>       <type>  <mnt_flags and options>                                                                                         <fs_mgr_flags>\r\n/dev/block/bootdevice/by-name/boot                           /boot             emmc    defaults                                                                                                        defaults\r\n/dev/block/bootdevice/by-name/recovery                       /recovery         emmc    defaults                                                                                                        defaults\r\n/dev/block/bootdevice/by-name/system                         /system           ext4    rw,barrier=1,discard                                                                                            wait\r\n/dev/block/bootdevice/by-name/userdata                       /data             ext4    nosuid,nodev,noatime,barrier=1,noauto_da_alloc                                                                  wait,check,encryptable=footer,formattable,length=-16384\r\n/dev/block/bootdevice/by-name/persist                        /persist          ext4    nosuid,nodev,barrier=1                                                                                          wait\r\n/dev/block/bootdevice/by-name/dsp                            /dsp              ext4    ro,nosuid,nodev,barrier=1                                                                                       wait\r\n/dev/block/bootdevice/by-name/modem                          /firmware         vfat    ro,shortname=lower,uid=1000,gid=1000,dmask=227,fmask=337                                                        wait\r\n/dev/block/bootdevice/by-name/bluetooth                      /bt_firmware      vfat    ro,shortname=lower,uid=1002,gid=3002,dmask=222,fmask=333                                                        wait\r\n/dev/block/bootdevice/by-name/misc                           /misc             emmc    defaults                                                                                                        defaults\r\n/dev/block/bootdevice/by-name/logo                           /logo             emmc    defaults                                                                                                        defaults\r\n\r\n/devices/soc/6a00000.ssusb/6a00000.dwc3/xhci-hcd.0.auto/usb* auto              auto    defaults                                                                                                        voldmanaged=usbdisk:auto\r\n","stderr":""}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":null,"stdout":".\r\n","stderr":""}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
debug: Downloading system-image file 12 of 12
debug: Downloading system-image file 11 of 12
debug: Downloading system-image file 10 of 12
debug: Downloading system-image file 9 of 12
debug: Downloading system-image file 8 of 12
debug: Downloading system-image file 7 of 12
debug: Downloading system-image file 6 of 12
debug: Downloading system-image file 5 of 12
debug: Downloading system-image file 4 of 12
debug: Downloading system-image file 3 of 12
debug: Downloading system-image file 2 of 12
debug: running step: {"type":"systemimage"}
debug: fastboot:boot done
command: fastboot: {"args":["boot","\"C:\\Users\\mem10\\AppData\\Roaming\\ubports\\oneplus3\\firmware\\halium-unlocked-recovery_oneplus3.img\""],"error":null,"stdout":"","stderr":"Sending 'boot.img' (20880 KB)                      OKAY [  0.467s]\r\nBooting                                            OKAY [  0.528s]\r\nFinished. Total time: 1.012s\r\n"}
debug: running step: {"type":"fastboot:boot","condition":{"var":"bootstrap","value":true},"file":"halium-unlocked-recovery_oneplus3.img","fallback_user_action":"recovery","group":"firmware"}
debug: fastboot:erase done
command: fastboot: {"args":["erase","cache"],"error":null,"stdout":"","stderr":"******** Did you mean to fastboot format this ext4 partition?\r\nErasing 'cache'                                    OKAY [  0.021s]\r\nFinished. Total time: 0.051s\r\n"}
debug: running step: {"type":"fastboot:erase","condition":{"var":"bootstrap","value":true},"partition":"cache"}
debug: fastboot:flash done
command: fastboot: {"args":["flash","recovery","\"C:\\Users\\mem10\\AppData\\Roaming\\ubports\\oneplus3\\firmware\\halium-unlocked-recovery_oneplus3.img\""],"error":null,"stdout":"","stderr":"Sending 'recovery' (20880 KB)                      OKAY [  0.480s]\r\nWriting 'recovery'                                 OKAY [  0.153s]\r\nFinished. Total time: 0.680s\r\n"}
debug: running step: {"type":"fastboot:flash","condition":{"var":"bootstrap","value":true},"flash":[{"partition":"recovery","file":"halium-unlocked-recovery_oneplus3.img","group":"firmware"}]}
command: fastboot: {"args":["devices"],"error":null,"stdout":"9109341c\tfastboot\r\n","stderr":""}
command: adb: {"args":["-P",5037,"reboot","bootloader"],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 reboot bootloader"},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
debug: running step: {"type":"adb:reboot","condition":{"var":"bootstrap","value":true},"to_state":"bootloader","fallback_user_action":"bootloader"}
debug: download done
info: Downloaded file 1 of 1
debug: checked: halium-unlocked-recovery_oneplus3.img
debug: running step: {"type":"download","condition":{"var":"bootstrap","value":true},"group":"firmware","files":[{"url":"http://cdimage.ubports.com/devices/halium-unlocked-recovery_oneplus3.img","checksum":"ca6359915a692523d7d12f6f0ca85e81d89328e7ad5bd46779e0af5c4b8c850b"}]}
debug: settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
debug: os config: {"name":"Ubuntu Touch","sanity_check":"Are you sure?","options":[{"var":"channel","name":"Channel","tooltip":"The release channel","link":"https://docs.ubports.com/en/latest/about/process/release-schedule.html","type":"select","remote_values":{"type":"systemimagechannels"}},{"var":"wipe","name":"Wipe Userdata","tooltip":"Wipe personal data","type":"checkbox"},{"var":"bootstrap","name":"Bootstrap","tooltip":"Flash system partitions using fastboot","type":"checkbox","value":true}],"prerequisites":[],"steps":[{"type":"download","condition":{"var":"bootstrap","value":true},"group":"firmware","files":[{"url":"http://cdimage.ubports.com/devices/halium-unlocked-recovery_oneplus3.img","checksum":"ca6359915a692523d7d12f6f0ca85e81d89328e7ad5bd46779e0af5c4b8c850b"}]},{"type":"adb:reboot","condition":{"var":"bootstrap","value":true},"to_state":"bootloader","fallback_user_action":"bootloader"},{"type":"fastboot:flash","condition":{"var":"bootstrap","value":true},"flash":[{"partition":"recovery","file":"halium-unlocked-recovery_oneplus3.img","group":"firmware"}]},{"type":"fastboot:erase","condition":{"var":"bootstrap","value":true},"partition":"cache"},{"type":"fastboot:boot","condition":{"var":"bootstrap","value":true},"file":"halium-unlocked-recovery_oneplus3.img","fallback_user_action":"recovery","group":"firmware"},{"type":"systemimage"},{"type":"adb:reboot","to_state":"recovery","fallback_user_action":"recovery"}],"slideshow":[]}
debug: no device detected: Error: stopped waiting
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":{"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\mem10\\AppData\\Local\\Temp\\1ZxQhKAjF1nHwFJLoBcXWazQ8mY\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 shell echo ."},"stdout":"","stderr":"error: no devices/emulators found\r\n"}
command: adb: {"args":["-P",5037,"start-server"],"error":null,"stdout":"","stderr":"* daemon not running; starting now at tcp:5037\r\n* daemon started successfully\r\n"}
debug: starting adb server on port 5037
command: adb: {"args":["-P",5037,"kill-server"],"error":null,"stdout":"","stderr":"cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: No connection could be made because the target machine actively refused it. (10061)\r\n"}
debug: killing all running adb servers
info: Welcome to the UBports Installer version 0.4.17-beta!

**Comment by mem101296** [comment]
The device is a Oneplus 3.
Seems to stop at an Android Recovery screen. The recovery has "Ubuntu Actions" and "Android Actions" listed.

**Comment by mem101296** [comment]
https://paste.ubuntu.com//p/rhw2hcyZFf/
