### ISSUE TITLE
Cannot install on a Nexus 5

### ISSUE THREAD

**Issue by andrewschott** [ubports/ubports-installer#1265]
(In case this point matters) I bought a Nexus 5 that had LineageOS installed from ebay to use Ubuntu Touch on.  I am on Fedora 32.  I downloaded and am using the appimage of .4-18b installer.

When running the installer and the setup tries pushing a systemimage file over I get an error regarding out of disk space.  Any idea on what to do here?

```
info: Welcome to the UBports Installer version 0.4.18-beta!
info: Downloaded file 1 of 2
info: Downloaded file 2 of 2
checked: keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz true
checked: version-10.tar.xz true
checked: device-e852c70a755d0212c840927a80c3d339d633e7a6d32f27de7de4cc66c247c628.tar.xz true
checked: ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz true
error: Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space
stack trace: Error: Error: Failed to push file 0: Error: Push failed: out of space
    at /tmp/.mount_ubportMYEV8z/resources/app.asar/src/system-image.js:84:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

EDIT:  Same thing after restoring to factory 6.0 ROM from Google.
EDIT2: While poking around I noticed a few folks who tried to use the twrp resize partition tool that was mentioned in another bug report to be the fix (doesnt work for me), I figured that since it appears that my /cache partition may be the issue, I would post my output of df and my partition data.  I reinstalled Android 6.0 and got into the phone via adb for easier copy/paste capabilities.

```
$ adb shell
shell@hammerhead:/ $ df
Filesystem               Size     Used     Free   Blksize
/dev                   927.5M    80.0K   927.4M   4096
/sys/fs/cgroup         927.5M    12.0K   927.5M   4096
/mnt                   927.5M     0.0K   927.5M   4096
/system               1009.3M   997.0M    12.3M   4096
/data                   26.8G   721.4M    26.1G   4096
/cache                 207.7M     4.4M   203.4M   4096
/persist                15.8M     4.2M    11.6M   4096
/firmware               64.0M    44.4M    19.6M   16384
/storage               927.5M     0.0K   927.5M   4096
/mnt/runtime/default/emulated: Permission denied
/storage/emulated       26.8G   721.4M    26.1G   4096
/mnt/runtime/read/emulated: Permission denied
/mnt/runtime/write/emulated: Permission denied
1|shell@hammerhead:/ $ cat /proc/partitions
major minor  #blocks  name

 179        0   30535680 mmcblk0
 179        1      65536 mmcblk0p1
 179        2       1024 mmcblk0p2
 179        3        512 mmcblk0p3
 179        4        512 mmcblk0p4
 179        5        512 mmcblk0p5
 179        6        512 mmcblk0p6
 179        7       2048 mmcblk0p7
 179        8       1024 mmcblk0p8
 179        9        512 mmcblk0p9
 179       10        512 mmcblk0p10
 179       11        512 mmcblk0p11
 179       12       3072 mmcblk0p12
 179       13       3072 mmcblk0p13
 179       14        512 mmcblk0p14
 179       15      16384 mmcblk0p15
 179       16      16384 mmcblk0p161
 179       17       3072 mmcblk0p17
 179       18      22528 mmcblk0p18
 179       19      22528 mmcblk0p19
 179       20      22528 mmcblk0p20
 179       21       3072 mmcblk0p21
 179       22        512 mmcblk0p22
 179       23        512 mmcblk0p23
 179       24        512 mmcblk0p24
 179       25    1548889 mmcblk0p25
 179       26      31250 mmcblk0p26
 179       27     215957 mmcblk0p27
 179       28   28551146 mmcblk0p28
 179       29          5 mmcblk0p29
 179       32       4096 mmcblk0rpmb
shell@hammerhead:/ $ 
```
EDIT3: Rooted (who cares, I dont plan on keeping android around any longer than it takes to get UT installed right?).  Heres my parted output:

```
(parted) p                                                                
Model: MMC SEM32G (sd/mmc)
Disk /dev/block/mmcblk0: 31.3GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name      Flags
 1      524kB   67.6MB  67.1MB  fat16        modem     msftdata
 2      67.6MB  68.7MB  1049kB               sbl1
 3      68.7MB  69.2MB  524kB                rpm
 4      69.2MB  69.7MB  524kB                tz
 5      69.7MB  70.3MB  524kB                sdi
 6      70.3MB  70.8MB  524kB                aboot
 7      70.8MB  72.9MB  2097kB               pad       msftdata
 8      72.9MB  73.9MB  1049kB               sbl1b
 9      73.9MB  74.4MB  524kB                tzb
10      74.4MB  75.0MB  524kB                rpmb
11      75.0MB  75.5MB  524kB                abootb
12      75.5MB  78.6MB  3146kB               modemst1
13      78.6MB  81.8MB  3146kB               modemst2
14      81.8MB  82.3MB  524kB                metadata
15      82.3MB  99.1MB  16.8MB               misc
16      99.1MB  116MB   16.8MB  ext4         persist
17      116MB   119MB   3146kB               imgdata
18      119MB   142MB   23.1MB               laf
19      142MB   165MB   23.1MB               boot
20      165MB   188MB   23.1MB               recovery
21      188MB   191MB   3146kB               fsg
22      191MB   192MB   524kB                fsc
23      192MB   192MB   524kB                ssd
24      192MB   193MB   524kB                DDR
25      193MB   1779MB  1586MB  ext4         system    msftdata
26      1779MB  1811MB  32.0MB               crypto    msftdata
27      1811MB  2032MB  221MB   ext4         cache     msftdata
28      2032MB  31.3GB  29.2GB  ext4         userdata  msftdata
29      31.3GB  31.3GB  5632B                grow      msftdata

(parted)                           
```

**Comment by andrewschott** [comment]
It ended up being what I thought, messed up partition sizes.  A nice chap from the xda fora helped me with finding a factory dump of the patition table via parted. 

https://forum.xda-developers.com/google-nexus-5/general/info-partition-list-nexus-5-t2517503

Once I deleted and recreated 25-29, I was able to get the UT installer to not barf.  No errors.  Just a success message.
