### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/system on /system failed: Invalid argument"}

### ISSUE THREAD

**Issue by wizzymt** [ubports/ubports-installer#1312]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/GTZq8ZzwjT/

**Comment by wizzymt** [comment]
error message:

error: Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/system on /system failed: Invalid argument"}
stack trace: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/system on /system failed: Invalid argument"}
    at /opt/ubports-installer/resources/app.asar/src/system-image.js:84:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
checked: device-81a2ed6434fb18760776da428af03dbd3b764b6453f7c76126d6e1666f247252.tar.xz true

**Comment by wizzymt** [comment]
I got one step further. 
under the menu with 
ubuntu action , android action , restart 
I chose android action, advanced, I wiped the system partition, all the data and went to restart to bootloader. 
After that I restart the ubport over the terminal with sudo. 
It seems to work for me now :)
