### ISSUE TITLE
Fastboot: error: Couldn't parse partition size '0x'.

### ISSUE THREAD

**Issue by Vince1171** [ubports/ubports-installer#1519]
I'm facing this error during the install process of Lineage 16 for the [Oneplus2](https://github.com/Vince1171/installer-configs/commit/ae243906a0a23999e8afcdcb11a0fd03522f6b51) while using the UBports Installer but this issue doesn't occure if I use fastboot installed with apt...
```
error: Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash boot \"/home/vince/.cache/ubports/oneplus2/LineageOS/unpacked/boot.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}
stack trace: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash boot \"/home/vince/.cache/ubports/oneplus2/LineageOS/unpacked/boot.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}
    at /opt/ubports-installer/resources/app.asar/node_modules/promise-android-tools/src/fastboot.js:90:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
```
vince@vince-mint:~$ /opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot flash boot /home/vince/.cache/ubports/oneplus2/LineageOS/unpacked/boot.img
fastboot: error: Couldn't parse partition size '0x'.
vince@vince-mint:~$ fastboot flash boot /home/vince/.cache/ubports/oneplus2/LineageOS/unpacked/boot.img
target reported max download size of 536870912 bytes
sending 'boot' (15624 KB)...
OKAY [  0.452s]
writing 'boot'...
OKAY [  0.140s]
finished. total time: 0.592s
vince@vince-mint:~$ /opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot --version
fastboot version 30.0.4-6686687
Installed as /opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot
vince@vince-mint:~$ fastboot --version
fastboot version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/fastboot
```

According to this [post](https://www.reddit.com/r/essential/comments/ihhedy/psa_solution_fastboot_error_couldnt_parse/), the solution is to use `fastboot flash:raw boot boot.img` instead of just `fastboot flash boot boot.img`

and I can confirm it works
```
vince@vince-mint:~$ /opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot flash boot /home/vince/.cache/ubports/oneplus2/LineageOS/unpacked/boot.img
fastboot: error: Couldn't parse partition size '0x'.
vince@vince-mint:~$ /opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot flash:raw boot /home/vince/.cache/ubports/oneplus2/LineageOS/unpacked/boot.img
Sending 'boot' (15624 KB)                          OKAY [  0.452s]
Writing 'boot'                                     OKAY [  0.134s]
Finished. Total time: 0.605s
```

I'm unfortunately not familiar enough with the project to PR a fix :/  

EDIT: I'm using version 0.6.0 of the installer

**Comment by NeoTheThird** [comment]
Caused by more extensive checking done in newer fastboot versions, the installer comes with the latest fastboot, instead of the old one shipped in ubuntu and debian. You'll need to set the raw flag as seen here: https://github.com/ubports/installer-configs/blob/master/v1/kugo.json#L88

**Comment by Vince1171** [comment]
fixed by adding `"raw": true` to the fastboot step
