### ISSUE TITLE
ubports-installer_0.8.0-beta_linux_x86_64.AppImage UI not working...

### ISSUE THREAD

**Issue by robiwan1** [ubports/ubports-installer#1573]
starting appimage (@ubuntu 20.04) spans many processes, but NO UI process. Starting from commandline says: $ ./ubports-installer_0.8.0-beta_linux_x86_64.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'graphql/language/printer'
Require stack:
- /tmp/.mount_ubportge31Ce/resources/app.asar/node_modules/graphql-request/dist/index.js
- /tmp/.mount_ubportge31Ce/resources/app.asar/node_modules/open-cuts-reporter/lib/module.cjs
- /tmp/.mount_ubportge31Ce/resources/app.asar/src/lib/reporter.js
- /tmp/.mount_ubportge31Ce/resources/app.asar/src/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_ubportge31Ce/resources/app.asar/node_modules/graphql-request/dist/index.js:85:17)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)

**Comment by NeoTheThird** [comment]
Is it possible that you downloaded the artifact immediately after the build was first published? The first build was faulty and was exchanged a few minutes later. Please try downloading the artifact again, it should be fixed now. Thanks!

**Comment by NeoTheThird** [comment]
No worries, thanks for reporting back! :)
