### ISSUE TITLE
checksum failed 

### ISSUE THREAD

**Issue by doniks** [ubports/ubports-installer#1591]
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-29-generic x64 NodeJS v12.16.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fc738ac9702a600079df4ac
Log: *N/A*

started deb in fastboot mode, started installer, deb detected, then it instructed me to reboot into bootloader mode, so I restarted it again into fastboot, then continue, then it asked me to boot to recovery, so I did that, then it seems it started downloading something, then it gave me an error about some checksum failed while downloading ... I didn't copy the verbatim error, tbh I thought this bugreporting software would capture and attach the log, but I can't see it anywhere now ....

**Comment by doniks** [comment]
found it: 
info: device detected: deb
info: preparing
info: checking previously downloaded firmware files
info: Downloaded file 0 of 1
info: downloading
info: downloading firmware files
info: Downloaded file 1 of 1
warn: lost connection to device
error: Error: systemimage: Error: Error: Failed to download latest version Error: Error: Checksum mismatch on file /home/peter/snap/ubports-installer/320/.cache/ubports/system-image/pool/ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz
stack trace: Error: Error: Failed to download latest version Error: Error: Checksum mismatch on file /home/peter/snap/ubports-installer/320/.cache/ubports/system-image/pool/ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz
    at /snap/ubports-installer/320/app/resources/app.asar/src/system-image.js:87:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by doniks** [comment]
ugh, upon trying a second time, I hit another error, filled out the reproduction for this new bug report, but seemingly that didn't go anywhere, so I'll just copy/paste it here

peter@hp:~$ ubports-installer 
Gtk-Message: 07:50:15.628: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:50:15.629: Failed to load module "canberra-gtk-module"

(ubports-installer:30310): GLib-GIO-CRITICAL **: 07:50:15.647: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: Welcome to the UBports Installer version 0.7.4-beta!

(ubports-installer:30310): GLib-GIO-CRITICAL **: 07:50:15.825: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: device detected: deb
error: Error: adb:format: Error: failed to format system: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/system on /system failed: Device or resource busy
stack trace: Error: failed to format system: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/system on /system failed: Device or resource busy
    at /snap/ubports-installer/320/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:670:15
    at /snap/ubports-installer/320/app/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by doniks** [comment]
riiiiight, no, it didn't ignore my second bug report, it just took 5 minutes to open a browser window with it.... 

**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-29-generic x64 NodeJS v12.16.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com/p/CgFVwrXX7z/


second attempt at installing. ubports recovery seems was installed and running, so I started again with: yes:wipe personal, no: do not bootstrap and yes: format system, but now it gave some adb error, I think something about mounting system partition if I saw it correctly (this is really annoying to type the reproduction while the error message is being hidden :( after it clearly was recorded )

**Comment by doniks** [comment]
third attempt: close the installer, adb shell, `mount`: I see all three `/data, / system, /cache` are mounted and empty (only lost+found folder). open the installer again, this time: no: wipe, no: bootstrap, no: format, then the installer fails again, this time: 

Error: adb:format: Error: failed to format cache: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy

**Comment by doniks** [comment]
fourth attempt, download the deb.json, delete the three "format" blocks at the bottom (cache, data, system) and restart the installer with that ... now the installation completes successfully, except, after telling me that it was successful, it is asking me to report a bug ... oh well, foreshadowing much? Sorry for lumping everything into one report, but it kinda is and isn't related. I can split them, or retry something if you need other logs, etc, just let me know

**Comment by NeoTheThird** [comment]
I'm sorry.

**Comment by doniks** [comment]
oh, please. don't worry! software has bugs. we'll get it fixed again eventually. I totally appreciate the work you've put into the installer. it is much better. it will get even better in the future ;) let me know if there is anything I can do

**Comment by doniks** [comment]
I tried this again and got the same mounting error. Then I looked at the config again, but now I'm getting more confused:
1. originally I thought that the installer tries to mount `/cache` but fails because it isn't mounted. The issue is tagged as device-config, so I looked at the config again to find anything that looks like check-if-mounted or ignore-mount-error, but I can't see anything, so I was about to suggest it's a missing feature that **mount action should check whether fs is mounted already**. however,
2. if this is about formatting, then it shouldn't mount it in the first place, right? it should be **un**mounted for formatting 🤔

fwiw, I'v also poked around for other related bug reports. it seems that
* https://github.com/ubports/ubports-installer/issues/1675 mentions mounting problems, but then after "Rolled device back to stock config" it worked, which I don't understand
* https://github.com/ubports/ubports-installer/issues/1849 mentions mounting problems, that were overcome by trying again ... which I also don't understand 

🤷

**Comment by doniks** [comment]
retried with 0.8.9-beta and got the same problem. after clicking "try again" (or is it called "retry", but I am sure I did NOT click "ignore") it proceeded with the installation. (sounds like #1849) 

```
peter@hp:~/docs/devel/ubports-installer$ ubports-installer
Gtk-Message: 12:47:10.541: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:47:10.551: Failed to load module "canberra-gtk-module"

(ubports-installer:22618): GLib-GIO-CRITICAL **: 12:47:11.215: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: Welcome to the UBports Installer version 0.8.9-beta!

(ubports-installer:22618): GLib-GIO-CRITICAL **: 12:47:19.769: g_settings_schema_source_lookup: assertion 'source != NULL' failed

(ubports-installer:22618): dbind-WARNING **: 12:47:23.048: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-YQbsjcKT2Y: No such file or directory
info: device detected: deb
info: Installing Ubuntu Touch on your Nexus 7 2013 LTE (deb)
info: configuring...
info: settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
error: Error: adb:format: Error: failed to format cache: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy
stack trace: Error: failed to format cache: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy
    at /snap/ubports-installer/365/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:658:15
    at /snap/ubports-installer/365/app/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: restart after error
info: Downloading 12 files
info: Downloaded file 1 of 12
info: Downloaded file 2 of 12
info: Downloaded file 3 of 12
info: Downloaded file 4 of 12
info: Downloaded file 5 of 12
```

**Comment by doniks** [comment]
I can also reconfirm the issue on flo (Nexus 7 2013 wifi).
