### ISSUE TITLE
[deb] Stuck on Google logo screen.

### ISSUE THREAD

**Issue by jbone899** [ubports/ubports-installer#1675]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Downloaded latest UB Ports installer and N7 G2 LTE (Deb) version,16.04 stable. Started upgrade to Ubuntu Touch. Known Bug Error message, could not mount SD card during install. Checked connection cable and restarted device in bootloader. Android Bootloader pulled up. Went to recovery option. Ubuntu touch recovery pulled up instead of Android TWRP. Ubuntu options and terminal were also available. Restarted to System. Unit froze on Google Logo screen for 10+ minutes. Repeated process to get back to Recovery. Wiped device and tried to install it again, no joy, same issue. My N7 G2 LTE (Deb) was running Unofficial Resurrection Remix version 6.2.1 (A8.1 "Oreo"). Rolled device back to stock config (A6 Marshmallow) using XDA Restock2. Tried again. Ubuntu Touch loaded successfully. 
You may want to include the unit needs to be running a Stock config, in order to load this software correctly. Thanks for all you do! I have an eBay store now that I am offering this software. I am donating a portion of each sale to UBPorts (once a month)

**Comment by doniks** [comment]
i tried to reproduce this, but I got stuck halfway during installing Resurrection Remix (RR). However, i see that in order to install RR one has to increase the system partition to at least 1.5GB. One way of doing this is this [1]. Amongst a few other partition modifications, it increases the system partition to ca 1.5GB and shrinks the cache partition to ca 75MB (they are adjacent). Maybe this is what eventually leads to the problem?

[1] https://forum.xda-developers.com/t/repartition-nexus-7-2013-repartition-flo-deb-16gb-32gb-ua-twrp.3844386/

**Comment by doniks** [comment]
ok, even though RR never actually booted, I had completed the repartitioning and afterwards tried to install UT. It fails with an out of space error. 

```
ubports-installer 
Gtk-Message: 14:41:32.427: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:41:32.453: Failed to load module "canberra-gtk-module"

(ubports-installer:32133): GLib-GIO-CRITICAL **: 14:41:33.246: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: Welcome to the UBports Installer version 0.8.9-beta!

(ubports-installer:32133): GLib-GIO-CRITICAL **: 14:41:46.222: g_settings_schema_source_lookup: assertion 'source != NULL' failed

(ubports-installer:32133): dbind-WARNING **: 14:41:48.697: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-YQbsjcKT2Y: No such file or directory
info: device detected: deb
info: Installing Ubuntu Touch on your Nexus 7 2013 LTE (deb)
info: configuring...
info: settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
error: Error: adb:format: Error: failed to format cache: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy
stack trace: Error: failed to format cache: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy
    at /snap/ubports-installer/365/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:658:15
    at /snap/ubports-installer/365/app/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: restart after error
info: Downloading 8 files
info: Downloaded file 1 of 8
info: Downloaded file 2 of 8
info: Downloaded file 3 of 8
info: Downloaded file 4 of 8
info: Downloaded file 5 of 8
info: Downloaded file 6 of 8
info: Downloaded file 7 of 8
info: Downloaded file 8 of 8
warn: undefined
error: Error: adb:push: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz' to '/cache/recovery/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz': remote No space left on device\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz: 1 file pushed, 0 skipped. 2.9 MB/s (367805316 bytes in 122.308s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz.asc: 1 file pushed, 0 skipped. 0.5 MB/s (488 bytes in 0.001s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz: 1 file pushed, 0 skipped. 2.8 MB/s (64505972 bytes in 21.693s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz.asc: 1 file pushed, 0 skipped. 1.7 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz: 1 file pushed, 0 skipped. 2.8 MB/s (1564 bytes in 0.001s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz.asc: 1 file pushed, 0 skipped. 1.1 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/version-17.tar.xz: 1 file pushed, 0 skipped. 1.0 MB/s (472 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/version-17.tar.xz.asc: 1 file pushed, 0 skipped. 1.6 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-signing.tar.xz: 1 file pushed, 0 skipped. 3.1 MB/s (940 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 1.7 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-master.tar.xz: 1 file pushed, 0 skipped. 3.2 MB/s (900 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 1.2 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubuntu_command: 1 file pushed, 0 skipped. 1.4 MB/s (716 bytes in 0.000s)\n13 files pushed, 0 skipped. 2.8 MB/s (432318808 bytes in 144.833s)"}
stack trace: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz' to '/cache/recovery/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz': remote No space left on device\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz: 1 file pushed, 0 skipped. 2.9 MB/s (367805316 bytes in 122.308s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubports-f2c28baec153476f4805867ebcefcc6965ea1f2b981414035a8ab6828af6c9ec.tar.xz.asc: 1 file pushed, 0 skipped. 0.5 MB/s (488 bytes in 0.001s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz: 1 file pushed, 0 skipped. 2.8 MB/s (64505972 bytes in 21.693s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz.asc: 1 file pushed, 0 skipped. 1.7 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz: 1 file pushed, 0 skipped. 2.8 MB/s (1564 bytes in 0.001s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz.asc: 1 file pushed, 0 skipped. 1.1 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/version-17.tar.xz: 1 file pushed, 0 skipped. 1.0 MB/s (472 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/version-17.tar.xz.asc: 1 file pushed, 0 skipped. 1.6 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-signing.tar.xz: 1 file pushed, 0 skipped. 3.1 MB/s (940 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 1.7 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-master.tar.xz: 1 file pushed, 0 skipped. 3.2 MB/s (900 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 1.2 MB/s (488 bytes in 0.000s)\n/home/peter/snap/ubports-installer/365/.cache/ubports/deb/Ubuntu Touch/ubuntu_command: 1 file pushed, 0 skipped. 1.4 MB/s (716 bytes in 0.000s)\n13 files pushed, 0 skipped. 2.8 MB/s (432318808 bytes in 144.833s)"}
    at ChildProcess.<anonymous> (/snap/ubports-installer/365/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:414:17)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:327:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:32133) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
info: Good bye!
```
