### ISSUE TITLE
New Download Failed

### ISSUE THREAD

**Issue by total4linux** [ubports/ubports-installer#1705]
**UBports Installer `0.8.2-beta` (deb)**
Environment: `LinuxMint 20 Ulyana linux 5.4.0-59-generic x64 NodeJS v12.16.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ff6b318203a7f00076454a5
Log: *N/A*

shell not configured

**Comment by NeoTheThird** [comment]
Fails to open the external link:

```
error: Error: uncaught exception at uncaughtException: ReferenceError: shell is not defined
stack trace: ReferenceError: shell is not defined
    at IpcMainImpl.<anonymous> (/opt/ubports-installer/resources/app.asar/src/lib/updater.js:87:3)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8475)
    at WebContents.emit (events.js:310:20)
```

**Comment by mkarpicki** [comment]
I am experiencing same with 0.8.8-beta on Ubuntu 20.04.4 LTS. 
Ubports installer opens and informs about update, immediately after trying to download this error appears
