### ISSUE TITLE
[karin] Flashing failed: {"error":{"code":1},"stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by ip6li** [ubports/ubports-installer#1747]
**UBports Installer `0.8.4-beta` (AppImage)**
Environment: `Ubuntu 20.10 Groovy Gorilla linux 5.8.0-40-generic x64 NodeJS v12.18.3`
Device: karin
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/600c2264203a7f000764874e
Log: https://paste.ubuntu.com/p/J8jGK2h7jw/

Use SG771 with LineageOS 14.1 installed and try to install UT

```
$ ./ubports-installer_0.8.4-beta_linux_x86_64.AppImage 
info: Welcome to the UBports Installer version 0.8.4-beta!
info: device detected: karin
warn: The device karin is not supported!
info: device selected: karin
info: Installing Ubuntu Touch on your Sony Xperia Z4 Tablet4 (SGP771) (karin)
info: configuring...
info: settings: {"channel":"16.04/community/anpok/devel","wipe":false,"bootstrap":true}
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"fastboot: error: Couldn't parse partition size '0x'."}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"fastboot: error: Couldn't parse partition size '0x'."}
    at /tmp/.mount_ubport5rFxL9/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1102:15
    at /tmp/.mount_ubport5rFxL9/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5295) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by NeoTheThird** [comment]
fixed by https://github.com/ubports/installer-configs/commit/a957b052cab64a1ed730af8a44b618f55f47bfb2
