### ISSUE TITLE
[mako] no space left on device error

### ISSUE THREAD

**Issue by matteo-gallo-bb** [ubports/ubports-installer#1825]
**UBports Installer `0.8.5-beta` (AppImage)**
Environment: `Debian GNU/Linux unknown linux 5.10.0-3-amd64 x64 NodeJS v12.18.3`
Device: mako
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6041467ab24e590007332590
Log: *N/A*

Tried to install on Nexus 4 with Android 5.1

**Comment by NeoTheThird** [comment]
```
command: spawn:start: {"cmd":["adb","-P",5037,"push","/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz","/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc","/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz","/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz.asc","/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz","/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc","/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz","/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz.asc","/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz","/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc","/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz","/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz.asc","/home/matteo/.cache/ubports/system-image/ubuntu_command","/cache/recovery/"]}
command: spawn:exit: {"cmd":["adb","-P",5037,"push","/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz","/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc","/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz","/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz.asc","/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz","/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc","/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz","/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz.asc","/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz","/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc","/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz","/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz.asc","/home/matteo/.cache/ubports/system-image/ubuntu_command","/cache/recovery/"],"code":1}
debug: attempting to handle Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\n/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 5.8 MB/s (392330372 bytes in 64.112s)\n/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 7.2 MB/s (473 bytes in 0.000s)\nadb: error: failed to copy '/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz' to '/cache/recovery/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz': remote No space left on device\n/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz: 1 file pushed, 0 skipped. 5.6 MB/s (71505616 bytes in 12.268s)\n/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz.asc: 1 file pushed, 0 skipped. 6.2 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 37.8 MB/s (1504 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 13.8 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz: 1 file pushed, 0 skipped. 13.3 MB/s (460 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz.asc: 1 file pushed, 0 skipped. 12.8 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz: 1 file pushed, 0 skipped. 26.5 MB/s (900 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 17.6 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz: 1 file pushed, 0 skipped. 32.0 MB/s (864 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 18.3 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/ubuntu_command: 1 file pushed, 0 skipped. 11.7 MB/s (728 bytes in 0.000s)\n13 files pushed, 0 skipped. 5.8 MB/s (463843282 bytes in 76.839s)"}
error: Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\n/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 5.8 MB/s (392330372 bytes in 64.112s)\n/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 7.2 MB/s (473 bytes in 0.000s)\nadb: error: failed to copy '/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz' to '/cache/recovery/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz': remote No space left on device\n/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz: 1 file pushed, 0 skipped. 5.6 MB/s (71505616 bytes in 12.268s)\n/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz.asc: 1 file pushed, 0 skipped. 6.2 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 37.8 MB/s (1504 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 13.8 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz: 1 file pushed, 0 skipped. 13.3 MB/s (460 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz.asc: 1 file pushed, 0 skipped. 12.8 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz: 1 file pushed, 0 skipped. 26.5 MB/s (900 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 17.6 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz: 1 file pushed, 0 skipped. 32.0 MB/s (864 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 18.3 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/ubuntu_command: 1 file pushed, 0 skipped. 11.7 MB/s (728 bytes in 0.000s)\n13 files pushed, 0 skipped. 5.8 MB/s (463843282 bytes in 76.839s)"}
stack trace: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\n/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 5.8 MB/s (392330372 bytes in 64.112s)\n/home/matteo/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 7.2 MB/s (473 bytes in 0.000s)\nadb: error: failed to copy '/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz' to '/cache/recovery/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz': remote No space left on device\n/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz: 1 file pushed, 0 skipped. 5.6 MB/s (71505616 bytes in 12.268s)\n/home/matteo/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz.asc: 1 file pushed, 0 skipped. 6.2 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 37.8 MB/s (1504 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 13.8 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz: 1 file pushed, 0 skipped. 13.3 MB/s (460 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/pool/version-13.tar.xz.asc: 1 file pushed, 0 skipped. 12.8 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz: 1 file pushed, 0 skipped. 26.5 MB/s (900 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 17.6 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz: 1 file pushed, 0 skipped. 32.0 MB/s (864 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/gpg/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 18.3 MB/s (473 bytes in 0.000s)\n/home/matteo/.cache/ubports/system-image/ubuntu_command: 1 file pushed, 0 skipped. 11.7 MB/s (728 bytes in 0.000s)\n13 files pushed, 0 skipped. 5.8 MB/s (463843282 bytes in 76.839s)"}
    at ChildProcess.<anonymous> (/tmp/.mount_ubportsU8Skv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:416:17)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:327:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

we're getting a "no space left on device error", this needs to be investigated

**Comment by MrT10001** [comment]
Hi, if the phone has had a custom ROM installed previously before going back to stock Android, it may show this error as the partition tables have been resized on the eMMC to accommodate the ROM. If you go to XDA Developers forum and search, someone has kindly written a re-partition tool that you can use to take it back to stock. It is not for the faint hearted and took a bit to work out. I had a Nexus 4 (Mako) that refused to install UBports, it would either hang with the above message or it would seem fail at the last moment and either come up with another message or hang at recovery. Re-partitioned it to stock twice and resolved it.

**Comment by UniversalSuperBox** [comment]
Hi @matteo-gallo-bb, please see the answer above for how you can install Ubuntu Touch on your Nexus 4.
