### ISSUE TITLE
couldnt install after fastboot window error in creating filesystem ext4, phone still shows FASTBOOT and a rabbit and a green droid

### ISSUE THREAD

**Issue by odarcan** [ubports/ubports-installer#1848]
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-66-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604baaed9442980007575452
Log: *N/A*

get a similar phone

**Comment by gibcheesepuffs** [comment]
Did you unlock bootloader and critical first?

**Comment by UniversalSuperBox** [comment]
The log contains errors which suggest not: 

```
command: exec: {"cmd":["fastboot","format:ext4","system"],"error":{"message":"Command failed: fastboot format:ext4 system\nmke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.006s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed","code":1},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: 699539c6-f87f-49d0-a5ac-de1a3b9f60a0\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.006s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
debug: attempting to handle Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: 699539c6-f87f-49d0-a5ac-de1a3b9f60a0\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.006s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
error: Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: 699539c6-f87f-49d0-a5ac-de1a3b9f60a0\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.006s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: 699539c6-f87f-49d0-a5ac-de1a3b9f60a0\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.006s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
    at /snap/ubports-installer/348/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1202:15
    at /snap/ubports-installer/348/app/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: restart after error
verbose: running step {"actions":[{"fastboot:format":{"partition":"system","type":"ext4"}}],"condition":{"var":"bootstrap","value":true}}
verbose: running fastboot action format
command: exec: {"cmd":["fastboot","format:ext4","system"],"error":{"message":"Command failed: fastboot format:ext4 system\nmke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.003s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed","code":1},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: c421f22e-2bf8-414e-bc9c-a164d549a27e\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.003s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
debug: attempting to handle Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: c421f22e-2bf8-414e-bc9c-a164d549a27e\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.003s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
error: Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: c421f22e-2bf8-414e-bc9c-a164d549a27e\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.003s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stdout":"Creating filesystem with 786432 4k blocks and 196608 inodes\nFilesystem UUID: c421f22e-2bf8-414e-bc9c-a164d549a27e\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912\n\nAllocating group tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nWriting inode tables:  0/24\b\b\b\b\b     \b\b\b\b\bdone                            \nCreating journal (16384 blocks): done\nWriting superblocks and filesystem accounting information:  0/24\b\b\b\b\b     \b\b\b\b\bdone","stderr":"mke2fs 1.45.4 (23-Sep-2019)\nSending 'system_b' (92 KB)                         OKAY [  0.003s]\nWriting 'system_b'                                 FAILED (remote: 'Flashing is not allowed in Lock State')\nfastboot: error: Command failed"}
    at /snap/ubports-installer/348/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1202:15
    at /snap/ubports-installer/348/app/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by gibcheesepuffs** [comment]
@odarcan you need to unlock bootloader and critical first. For the you need to download platform-tools and extract them. Then from the extracted folder, you need to open cmdline or shell and then set your device in fastboot mode and run these commands:

fastboot flashing unlock
fastboot flashing unlock_critical

(if device does not reboot automatically)

fastboot reboot

This process will wipe your data on phone. Afterwards you need to run ubports installer again.

**Comment by UniversalSuperBox** [comment]
Since this report has not seen any activity for months, I will assume it has been resolved. Please let us know if that is not the case.
