### ISSUE TITLE
Kugo Automaticalli reboots while "Pushing Ubuntu Touch files..."

### ISSUE THREAD

**Issue by hasenbalg** [ubports/ubports-installer#1892]
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: kugo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6067519b470a860007576361
Log: *N/A*

Error says: Connection to device lost:

My log is: huhu@pc:~/Downloads$  ubports-installer 
Gtk-Message: 18:50:06.624: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:50:06.625: Failed to load module "canberra-gtk-module"

(ubports-installer:2419686): GLib-GIO-CRITICAL **: 18:50:06.633: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: Welcome to the UBports Installer version 0.8.7-beta!

(ubports-installer:2419686): GLib-GIO-CRITICAL **: 18:50:06.684: g_settings_schema_source_lookup: assertion 'source != NULL' failed
info: device detected: kugo
info: Installing Ubuntu Touch on your Sony Xperia X Compact (F5321) (kugo)
info: configuring...
info: settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":true}
info: Downloading 12 files
info: Downloaded file 1 of 12
info: Downloaded file 2 of 12
info: Downloaded file 3 of 12
info: Downloaded file 4 of 12
info: Downloaded file 5 of 12
info: Downloaded file 6 of 12
info: Downloaded file 7 of 12
info: Downloaded file 8 of 12
info: Downloaded file 9 of 12
info: Downloaded file 10 of 12
info: Downloaded file 11 of 12
info: Downloaded file 12 of 12
warn: lost connection to device
info: Downloading 8 files
info: Downloaded file 1 of 8
info: Downloaded file 2 of 8
info: Downloaded file 3 of 8
info: Downloaded file 4 of 8
info: Downloaded file 5 of 8
info: Downloaded file 6 of 8
info: Downloaded file 7 of 8
info: Downloaded file 8 of 8
info: Good bye!
error: Error: adb:wait: Error: {"error":{"code":1,"cmd":"adb -P 5037 wait-for-any-any"},"stderr":"error: protocol fault (couldn't read status): Success"}
stack trace: Error: {"error":{"code":1,"cmd":"adb -P 5037 wait-for-any-any"},"stderr":"error: protocol fault (couldn't read status): Success"}
    at /snap/ubports-installer/348/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
error: undefined

**Comment by CeeJay333** [comment]
I can confirm this. I have just encountered the same problem using the .deb and .appimage

**Comment by hasenbalg** [comment]
BTW: the reboot loop stops when i pull the USB cable.

**Comment by Sythelux** [comment]
I think it might be related to this: https://github.com/ubports/ubports-installer/issues/2082

I posted the forum thread that might help with that exact same issue there.
