### ISSUE TITLE
Cannot install on Nexus 7

### ISSUE THREAD

**Issue by drewmoseley** [ubports/ubports-installer#1912]
**UBports Installer `0.8.7-beta` (AppImage)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.11.0-7612-generic x64 NodeJS v12.18.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/607734f6460e7b00078681e2
Log: *N/A*

I just tried to run the install and received an error. 

info: Welcome to the UBports Installer version 0.8.7-beta!
info: UBports Installer restarting...
info: device selected: flo
info: Installing Ubuntu Touch on your Nexus 7 2013 WiFi (flo)
info: configuring...
error: Error: preparing: TypeError: Cannot read property 'codename' of null
stack trace: TypeError: Cannot read property 'codename' of null
    at SystemimagePlugin.remote_values__channels (/tmp/.mount_ubportvhO6cR/resources/app.asar/src/core/plugins/systemimage/plugin.js:81:46)
    at /tmp/.mount_ubportvhO6cR/resources/app.asar/src/core/plugins/index.js:89:51
    at async Promise.all (index 0)
warn: restart after error

**Comment by drewmoseley** [comment]
Not sure what happened but I tried again and now it seems to work.
