### ISSUE TITLE
yggdrasil: flashing ubports -> Volla OS failed first time, succeeded second time

### ISSUE THREAD

**Issue by osmith42** [ubports/ubports-installer#1940]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Debian GNU/Linux 10 buster linux 4.19.0-16-amd64 x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60956978094ace0007d225b4
Log: https://paste.ubuntu.com/p/tpFvRpnTQn/

First run errors with the following, and SIM doesn't work after the installation (see #1612):

> `error: Error: adb:shell: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir /mnt/vendor/nvdata"},"stderr":"error: exec '/system/bin/sh' failed: No such file or directory"}`

Second run succeeded:
https://ubports.open-cuts.org/run/6098e5979fa18d0007df1f21

**Comment by StefanYohansson** [comment]
same here. OS: Ubuntu 20.04.1 LTS
Target OS: VollaOS

```
error: Error: adb:shell: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir /mnt/vendor/nvdata"},"stderr":"error: exec '/system/bin/sh' failed: No such file or directory"}
stack trace: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir /mnt/vendor/nvdata"},"stderr":"error: exec '/system/bin/sh' failed: No such file or directory"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

**Comment by probonopd** [comment]
As of 0.9.6-beta, flashing from Ubuntu Touch to Volla OS doesn't work at all. When it tries to reboot the phone into fastboot mode, the phone just reboots into Ubuntu Touch.

**Comment by JamiKettunen** [comment]
May I ask you to try this again? https://github.com/ubports/installer-configs/pull/215 should solve this finally as the fix was moved to VollaOS side instead of relying on the installer to do the work :)

**Comment by probonopd** [comment]
Thanks @JamiKettunen. Unfortunately I don't currently have a free device to test with.
