### ISSUE TITLE
Getting error saying halium-boot-land.img No such file or directory

### ISSUE THREAD

**Issue by shikharka** [ubports/ubports-installer#2010]
**UBports Installer `0.8.8-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-59-generic x64 NodeJS v12.18.3`
Device: land
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com/p/3yKZPZSXZq/

Not sure if i need to download something or what to do next. Also, in earlier step the channel drop down was blank and without option

**Comment by marmistrz** [comment]
I'm affected by the same issue

**Comment by arkhi** [comment]
I too have the same issue with a Redmi 3s (land). The installation won’t work because there is no release available when choosing the Release channel:

![image](https://user-images.githubusercontent.com/277773/130366503-ee858a97-2228-439c-aafe-eab126690804.png)

- The recovery partition is created and bootable.
- The environment is: `Ubuntu 20.04.3 LTS Focal Fossa linux 5.4.0-81-generic x64 NodeJS v12.18.3`
- Running the AppImage version of the installer, I get the following:

```cli
$ ./ubports-installer_0.8.8-beta_linux_x86_64.AppImage --verbose
info: Welcome to the UBports Installer version 0.8.8-beta!
info: device detected: land
info: Installing Ubuntu Touch on your Xiaomi Redmi 3S 3X 3SP (land)
info: configuring...
info: settings: {"channel":null,"wipe":false,"bootstrap":true}
verbose: running step {"actions":[{"core:download":{"group":"firmware","files":[{"url":"https://cdimage.ubports.com/devices/land/recovery.img","checksum":{"sum":"4468a0c48e719a40273e4de1b1e0e6793e945cd665a812567990cb1b39a61b1f","algorithm":"sha256"}},{"url":"https://github.com/Ubports-Land/Ubports-CI/raw/master/splash.img","checksum":{"sum":"9b91dfb62c80cc533303687e132194a789da867524cbf4518d5e2bfa175e7bbd","algorithm":"sha256"}}]}}],"condition":{"var":"bootstrap","value":true}}
verbose: running core action download
verbose: running step {"actions":[{"adb:reboot":{"to_state":"bootloader"}}],"fallback":[{"core:user_action":{"action":"bootloader"}}],"condition":{"var":"bootstrap","value":true}}
verbose: running adb action reboot
verbose: running core action user_action
verbose: running step {"actions":[{"fastboot:wait":null}]}
verbose: running fastboot action wait
verbose: running step {"actions":[{"fastboot:flash":{"partitions":[{"partition":"recovery","file":"recovery.img","group":"firmware"},{"partition":"splash","file":"splash.img","group":"firmware"}]}}],"condition":{"var":"bootstrap","value":true}}
verbose: running fastboot action flash
verbose: running step {"actions":[{"fastboot:format":{"partition":"cache"}}],"condition":{"var":"bootstrap","value":true}}
verbose: running fastboot action format
verbose: skipping step {"actions":[{"fastboot:format":{"partition":"userdata"}}],"condition":{"var":"wipe","value":true}}
verbose: running step {"actions":[{"fastboot:boot":{"group":"firmware","file":"recovery.img"}}],"fallback":[{"core:user_action":{"action":"recovery"}}],"condition":{"var":"bootstrap","value":true}}
verbose: running fastboot action boot
verbose: running step {"actions":[{"systemimage:install":null}]}
verbose: running systemimage action install
error: Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportimt6WH/resources/app.asar/src/core/plugins/systemimage/api.js:81:48
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: restart after error
verbose: running step {"actions":[{"systemimage:install":null}]}
verbose: running systemimage action install
error: Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportimt6WH/resources/app.asar/src/core/plugins/systemimage/api.js:81:48
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:59075) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```
I see there is a way to run the installer with a custom config file with `--file`. I’ll try to search in that direction now.

**Comment by arkhi** [comment]
> I see there is a way to run the installer with a custom config file with `--file`. I’ll try to search in that direction now.

The [original config file](https://github.com/ubports/installer-configs/blob/master/v2/devices/land.yml) does not list any release; only the recovery, boot and splash images are loaded, so I guess _land_ is not ready yet. :)

@areyoudeveloper: I see you’re the only one who has been working on the file. Do you have any info on the status of the ubports version for _land_ on your side?

**Comment by areyoudeveloper** [comment]
> Mmm… I don’t see what I did wrong but it does not work with the following:
> 
> 1. I downloaded the [file from the commit you referenced](https://raw.githubusercontent.com/areyoudeveloper/installer-configs/dd9a95ad19c1bb0a9351284b830bf1015a4114dd/v2/devices/land.yml) in the same folder as the AppImage file.
> 2. I then ran `./ubports-installer_0.8.8-beta_linux_x86_64.AppImage -f land.yml -vv`
> 3. The release channel is empty and the installation fails with the following log:
> 
> ```
> info: Welcome to the UBports Installer version 0.8.8-beta!
> info: Installing Ubuntu Touch on your Xiaomi Redmi 3S 3X 3SP (land)
> info: configuring...
> info: settings: {"channel":null,"wipe":false,"bootstrap":true}
> verbose: running step {"actions":[{"core:download":{"group":"firmware","files":[{"url":"https://cdimage.ubports.com/devices/land/recovery.img","checksum":{"sum":"4468a0c48e719a40273e4de1b1e0e6793e945cd665a812567990cb1b39a61b1f","algorithm":"sha256"}},{"url":"https://github.com/Ubports-Land/Ubports-CI/raw/master/splash.img","checksum":{"sum":"9b91dfb62c80cc533303687e132194a789da867524cbf4518d5e2bfa175e7bbd","algorithm":"sha256"}}]}}],"condition":{"var":"bootstrap","value":true}}
> verbose: running core action download
> debug: checking previously downloaded firmware files
> verbose: running step {"actions":[{"adb:reboot":{"to_state":"bootloader"}}],"fallback":[{"core:user_action":{"action":"bootloader"}}],"condition":{"var":"bootstrap","value":true}}
> verbose: running adb action reboot
> debug: attempting to handle Error: no device
> verbose: running core action user_action
> verbose: running step {"actions":[{"fastboot:wait":null}]}
> verbose: running fastboot action wait
> verbose: running step {"actions":[{"fastboot:flash":{"partitions":[{"partition":"recovery","file":"recovery.img","group":"firmware"},{"partition":"splash","file":"splash.img","group":"firmware"}]}}],"condition":{"var":"bootstrap","value":true}}
> verbose: running fastboot action flash
> verbose: running step {"actions":[{"fastboot:format":{"partition":"cache"}}],"condition":{"var":"bootstrap","value":true}}
> verbose: running fastboot action format
> verbose: skipping step {"actions":[{"fastboot:format":{"partition":"userdata"}}],"condition":{"var":"wipe","value":true}}
> verbose: running step {"actions":[{"fastboot:boot":{"group":"firmware","file":"recovery.img"}}],"fallback":[{"core:user_action":{"action":"recovery"}}],"condition":{"var":"bootstrap","value":true}}
> verbose: running fastboot action boot
> verbose: running step {"actions":[{"systemimage:install":null}]}
> verbose: running systemimage action install
> debug: attempting to handle Error: 404
> error: Error: systemimage:install: Error: 404
> stack trace: Error: 404
>     at /tmp/.mount_ubportVYJaKh/resources/app.asar/src/core/plugins/systemimage/api.js:81:48
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> warn: error ignored
> verbose: running step {"actions":[{"adb:reboot":{"to_state":"recovery"}}],"fallback":[{"core:user_action":{"action":"recovery"}}]}
> verbose: running adb action reboot
> verbose: running step {"actions":[{"core:end":null}]}
> verbose: running core action end
> info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
> (node:24512) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> info: Good bye!
> ```

Uh yes I'm forgot land still not added to channel that still WIP

**Comment by shikharka** [comment]
Any update on this?

**Comment by areyoudeveloper** [comment]
Should be working now

**Comment by arkhi** [comment]
’Works like a charm, Thank you!

I had to struggle a bit to get the installer to do its job, and I was first wondering if the update had worked when the screen was lit but greyed out.

In the end, waiting for the install to finish its business paid off. I can have Ubuntu on my phone. :heart:
