### ISSUE TITLE
]install redmi 4x

### ISSUE THREAD

**Issue by ankzfu** [ubports/ubports-installer#2047]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 6.1.7600 win32 6.1.7600 x64 19041 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com/p/cmqSRrJwWD/

can't reboot from fastboot after clean partition

**Comment by galaxxyafonso** [comment]
I think this is the part that glitched out on your logs.

```
command: exec: {"cmd":["adb","-P",5037,"shell","mount -a"],"error":{"message":"Command failed: C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mount -a\nerror: closed","code":1},"stderr":"error: closed"}
command: exec: {"cmd":["adb","-P",5037,"shell","cat /etc/recovery.fstab"],"error":{"message":"Command failed: C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell cat /etc/recovery.fstab\nerror: closed","code":1},"stderr":"error: closed"}
command: exec: {"cmd":["adb","-P",5037,"shell","rm -rf /cache/*"],"error":{"message":"Command failed: C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell rm -rf /cache/*\nerror: closed","code":1},"stderr":"error: closed"}
command: exec: {"cmd":["adb","-P",5037,"shell","mkdir -p /cache/recovery"],"error":{"message":"Command failed: C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery\nerror: closed","code":1},"stderr":"error: closed"}
debug: attempting to handle Error: {"error":{"code":1,"cmd":"C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: closed"}
error: Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: closed"}
stack trace: Error: {"error":{"code":1,"cmd":"C:\\Users\\ANGGAF~1\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: closed"}
    at C:\Users\ANGGAF~1\AppData\Local\Temp\1raG3Aut6N5DTMPVp2eiGFFUdbP\resources\app.asar.unpacked\node_modules\promise-android-tools\lib\module.cjs:117:20
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
**warn: error ignored**
```

I can't confirm it to you, but thats what i found, because you did not elaborate that much on your problem!

`GalaxxyAfonso - some random developer`

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
