### ISSUE TITLE
Got 'Cannot read property 'action__wait' of undefined in the last step (volume up+power)

### ISSUE THREAD

**Issue by DavidVentura** [ubports/ubports-installer#2075]
**UBports Installer `0.8.8-beta` (AppImage)**
Environment: `Ubuntu 20.10 Groovy Gorilla linux 5.8.0-63-generic x64 NodeJS v12.18.3`
Device: beryllium
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Install on beryllium, last step fails

```
ings: {"channel":"16.04/arm64/android9/stable","wipe":true,"bootstrap":true}
info: Downloading 3 files
info: Downloaded file 1 of 3
info: Downloaded file 2 of 3
info: Downloaded file 3 of 3
warn: aborting run...
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: restart after error
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: restart after error
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: error ignored
info: Downloading 14 files
info: Downloaded file 1 of 14
info: Downloaded file 2 of 14
info: Downloaded file 3 of 14
info: Downloaded file 4 of 14
info: Downloaded file 5 of 14
info: Downloaded file 6 of 14
info: Downloaded file 7 of 14
info: Downloaded file 8 of 14
info: Downloaded file 9 of 14
info: Downloaded file 10 of 14
info: Downloaded file 11 of 14
info: Downloaded file 12 of 14
info: Downloaded file 13 of 14
info: Downloaded file 14 of 14
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: error ignored
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: restart after error
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: restart after error
error: Error: unknown: TypeError: Cannot read property 'action__wait' of undefined
stack trace: TypeError: Cannot read property 'action__wait' of undefined
    at /tmp/.mount_ubportYzTas7/resources/app.asar/src/core/plugins/index.js:74:29
warn: error ignored
info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
(node:4091) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by Vistaus** [comment]
I get the same “undefined” error as in the title.

UBports Installer 0.8.8-beta (DEB)
Environment: Deepin 20.2.3 (based on Debian 11)
Device: Xiaomi Poco F1 (beryllium)
Target OS: Ubuntu Touch

How do I get past this error and actually install Ubuntu Touch?

**Comment by DavidVentura** [comment]
i tried again and next time it worked

**Comment by Vistaus** [comment]
You're lucky then. I tried it multiple times now, but no luck :-(

The log shows:

`{"level":"verbose","message":"running core action download"}
{"level":"debug","message":"checking previously downloaded Ubuntu Touch files"}
{"level":"info","message":"Downloading 9 files"}
{"level":"debug","message":"downloading Ubuntu Touch files"}
{"level":"info","message":"Downloaded file 1 of 9"}
{"level":"info","message":"Downloaded file 2 of 9"}
{"level":"info","message":"Downloaded file 3 of 9"}
{"level":"info","message":"Downloaded file 4 of 9"}
{"level":"info","message":"Downloaded file 5 of 9"}
{"level":"info","message":"Downloaded file 6 of 9"}
{"level":"info","message":"Downloaded file 7 of 9"}
{"level":"info","message":"Downloaded file 8 of 9"}
{"level":"info","message":"Downloaded file 9 of 9"}
{"level":"verbose","message":"running core action write"}
{"level":"verbose","message":"running adb action wait"}
{"level":"debug","message":"attempting to handle TypeError: Cannot read property 'action__wait' of undefined"}
{"level":"error","message":"Error: unknown: TypeError: Cannot read property 'action__wait' of undefined\nstack trace: TypeError: Cannot read property 'action__wait' of undefined\n    at /opt/ubports-installer/resources/app.asar/src/core/plugins/index.js:74:29"}`

**Comment by Vistaus** [comment]
UPDATE: got it to work by following the older instructions over here:
https://forum.xda-developers.com/t/rom-beta-ubuntu-touch-for-poco-f1-ota-official-installer-halium-9-pie-based.4133513/post-85092245
