### ISSUE TITLE
Certificate expired when sending stats

### ISSUE THREAD

**Issue by sergiusens** [ubports/ubports-installer#2088]
This is what I get
```
info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
(node:686903) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
error: Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired
stack trace: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired
    at /snap/ubports-installer/352/app/resources/app.asar/node_modules/open-cuts-reporter/lib/module.cjs:111:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: error ignored
```

When using UBports Installer version 0.8.8-beta from

```
$ snap list ubports-installer 
Nombre             Versión     Rev  Seguimiento    Editor   Notas
ubports-installer  0.8.8-beta  352  latest/stable  ubports  -
```

**Comment by NeoTheThird** [comment]
fixed
