### ISSUE TITLE
Noisly log output: ChildProcess.exithandler (child_process.js:282:12)

### ISSUE THREAD

**Issue by paul-hammant** [ubports/ubports-installer#216]
For my finickity MeizuPro5, I see this is the log repeated every few seconds:

```
debug: adb shell: echo 1
debug:  Error: Command failed: adb -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
```

Maybe it would be better if the excption's stack trace was not put out to the log ad infinitum?

**Comment by skerit** [comment]
I'm getting the same thing with my BQ M10 FHD, but I'd argue the problem is not the noisy output, but that it can't ever find the damn device!
