### ISSUE TITLE
Install failed sargo

### ISSUE THREAD

**Issue by Justinzobel** [ubports/ubports-installer#2357]
**UBports Installer `0.8.9-beta` (AppImage)**
Environment: `Fedora Linux 35 KDE Plasma linux 5.15.10-200.fc35.x86_64 x64 NodeJS v12.18.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Attempt to install on Pixel 3a. It could not find the device during initial startup either and device was in fastboot mode.

```
adb --version Android Debug Bridge version 1.0.41 Version 31.0.2-android-tools Installed as /usr/bin/adb
fastboot --version fastboot version 31.0.2-android-tools Installed as /usr/bin/fastboot
```

stdout
```
./ubports-installer_0.8.9-beta_linux_x86_64.AppImage 
info: Welcome to the UBports Installer version 0.8.9-beta!
error: Error: plugin wait(): Error: {"message":"Unexpected getvar return: < waiting for any device >","name":"fastboot"}
stack trace: Error: {"message":"Unexpected getvar return: < waiting for any device >","name":"fastboot"}
    at PluginIndex.__pluginErrorHandler (/tmp/.mount_ubportWcBugt/resources/app.asar/src/core/plugins/index.js:193:11)
    at /tmp/.mount_ubportWcBugt/resources/app.asar/src/core/plugins/index.js:151:24
    at /tmp/.mount_ubportWcBugt/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: restart after error
info: UBports Installer restarting...
warn: Plugin error handler for plugin adb failed to parse error message: TypeError: Assignment to constant variable.
info: device selected: sargo
info: Installing Ubuntu Touch on your Google Pixel 3a/3a XL (sargo)
info: configuring...
error: Error: preparing: TypeError: Cannot read property 'codename' of null
stack trace: TypeError: Cannot read property 'codename' of null
    at SystemimagePlugin.remote_values__channels (/tmp/.mount_ubportWcBugt/resources/app.asar/src/core/plugins/systemimage/plugin.js:81:46)
    at /tmp/.mount_ubportWcBugt/resources/app.asar/src/core/plugins/index.js:93:51
    at async Promise.all (index 0)
warn: restart after error
error: Error: uncaught exception at uncaughtException: TypeError: Cannot read property 'condition' of undefined
stack trace: TypeError: Cannot read property 'condition' of undefined
    at Core.step (/tmp/.mount_ubportWcBugt/resources/app.asar/src/core/core.js:292:31)
    at Timeout._onTimeout (/tmp/.mount_ubportWcBugt/resources/app.asar/src/core/core.js:361:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:20939) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by Justinzobel** [comment]
After closing and restarting the AppImage it has now downloaded and is installing.

Used twrp to get to recovery mode when prompted, more files downloaded and it said it finished successfully and to wait up to 5 minutes for it to finish it's processes. For now it's just sitting on a UBP recovery screen with reboot/factory reset and advanced buttons plus halium 9 / slot b buttons at the bottom.

**Comment by Justinzobel** [comment]
I left it 5 minutes and tried rebooting but nothing happened, tried the devel channel as well, same result :(
