### ISSUE TITLE
Installation failed as /cache/recovery partitions could not be created

### ISSUE THREAD

**Issue by vitay** [ubports/ubports-installer#2508]
**UBports Installer `0.8.8-beta` (AppImage)**
Environment: `ManjaroLinux 21.2.5 Qonos linux 5.10.105-1-MANJARO x64 rolling NodeJS v12.18.3`
Device: frieza
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I followed the steps indicated by the installer. The tablet went into recovery mode and nothing happened, the installer was waiting for the device. I restarted the tablet, the installer threw an error about the recovery partition not existing, I ignored it and the installer concluded the install was successful. Still Android on the tablet, though (it was originally the Ubuntu version, but quite unusable in 2016 so I installed Android)...

Here is the log:

```
info: Welcome to the UBports Installer version 0.8.8-beta!
info: device detected: Aquaris_M10_FHD
warn: The device Aquaris_M10_FHD is not supported!
info: device selected: frieza
info: Installing Ubuntu Touch on your Bq Aquaris M10 FHD (frieza)
info: configuring...
info: settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'failed to get download permission for partition 'recovery'')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'failed to get download permission for partition 'recovery'')fastboot: error: Command failed"}
    at /tmp/.mount_ubport9AMQwU/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1100:15
    at /tmp/.mount_ubport9AMQwU/resources/app.asar.unpacked/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
warn: error ignored
info: Downloading 10 files
info: Downloaded file 1 of 10
info: Downloaded file 2 of 10
info: Downloaded file 3 of 10
info: Downloaded file 4 of 10
info: Downloaded file 5 of 10
info: Downloaded file 6 of 10
info: Downloaded file 7 of 10
info: Downloaded file 8 of 10
info: Downloaded file 9 of 10
info: Downloaded file 10 of 10
error: Error: adb:push: Error: {"error":{"code":1},"stdout":"adb: error: target '/cache/recovery/' is not a directory"}
stack trace: Error: {"error":{"code":1},"stdout":"adb: error: target '/cache/recovery/' is not a directory"}
    at ChildProcess.<anonymous> (/tmp/.mount_ubport9AMQwU/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:414:17)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:327:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
warn: undefined
warn: error ignored
info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
(node:7544) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by NeoTheThird** [comment]
If the device is running android, it needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) before the installer can work.
