### ISSUE TITLE
JingPad A1 - after flashing the firmware installation process fails

### ISSUE THREAD

**Issue by tsebastiani** [ubports/ubports-installer#2522]
ubports-installer version : 0.8.9-beta - 0.9.2-beta

After the flashing of the firmware, ubports asks to reboot in recovery mode to finish the installation, but actually fails giving this error in the console (and the same on the installation window)

`error: Error: systemimage:install: TypeError: Cannot read property 'status' of undefined
stack trace: TypeError: Cannot read property 'status' of undefined
    at /Applications/ubports-installer.app/Contents/Resources/app.asar/src/core/plugins/systemimage/api.js:81:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by NeoTheThird** [comment]
Okay, two things going on here. First, we messed up our error handling. Second, the stable channel seems to be empty:
https://system-image.ubports.com/16.04/arm64/android9/stable/jingpad_a1/index.json
```
{
    "global": {
        "generated_at": "Fri Mar 18 17:18:31 UTC 2022"
    },
    "images": []
}
```

Any idea how to solve the second part of the problem @Flohack74? Can we prevent channels without images from being listed in `channels.json`?

For the users experiencing this rn, please select `16.04/arm64/android9/devel` as a channel in the meantime. Thanks!

**Comment by amartinz** [comment]
Should be fixed by https://github.com/ubports/ubports-installer/pull/2525 with installer version `0.9.5-beta` and above

**Comment by NeoTheThird** [comment]
Well, i wanted to wait for the [channel to be fixed](http://system-image.ubports.com/16.04/arm64/android9/stable/jingpad_a1/index.json). But i don't know if that's happening.

**Comment by Flohack74** [comment]
I will try to look into it. My knowledge of Python is minimal, but I know approximately where this is generated
