### ISSUE TITLE
Plugin error handler for plugin adb failed to parse error message: TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by paliwaljee** [ubports/ubports-installer#2528]
**UBports Installer `0.9.2-beta` (exe)**
Environment: `Microsoft Windows 11 Home Single Language 10.0.22000 Windows 10.0.22000 x64 22000 0.0 NodeJS v16.13.0`
Device: [(device not yet detected)]
(https://devices.ubuntu-touch.io/device/(device not yet detected))
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623b7c745f2433000898d52c

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Two errors going on here. One unhandled problem in ADB, which will be fixed in [promise-android-tools 4.0.10](https://github.com/ubports/promise-android-tools/pull/63). Then, we're doing weird things by [assigning](https://github.com/ubports/ubports-installer/blob/7f6531bab29b3a0b8dc9db09039ab1571ba29229/src/core/plugins/index.js#L193) to a [const](https://github.com/ubports/ubports-installer/blob/7f6531bab29b3a0b8dc9db09039ab1571ba29229/src/core/plugins/index.js#L173).

```
command: exec: {"cmd":["adb","-P",5037,"shell","getprop ro.product.device"],"error":{"message":"Command failed: C:\\Users\\lalit\\AppData\\Local\\Temp\\26QXuFeDBKOo01Gy82McrKkqlwQ\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell getprop ro.product.device\nerror: protocol fault (couldn't read status): connection reset","code":1},"stderr":"error: protocol fault (couldn't read status): connection reset"}
warn: Plugin error handler for plugin adb failed to parse error message: TypeError: Assignment to constant variable.
error: Error: plugin wait(): Error: {"message":"{\"error\":{\"code\":1,\"cmd\":\"C:\\\\Users\\\\lalit\\\\AppData\\\\Local\\\\Temp\\\\26QXuFeDBKOo01Gy82McrKkqlwQ\\\\resources\\\\app.asar.unpacked\\\\node_modules\\\\android-tools-bin\\\\dist\\\\win32\\\\x86\\\\adb.exe -P 5037 shell getprop ro.product.device\"},\"stderr\":\"error: protocol fault (couldn't read status): connection reset\"}","name":"adb"}
stack trace: Error: {"message":"{\"error\":{\"code\":1,\"cmd\":\"C:\\\\Users\\\\lalit\\\\AppData\\\\Local\\\\Temp\\\\26QXuFeDBKOo01Gy82McrKkqlwQ\\\\resources\\\\app.asar.unpacked\\\\node_modules\\\\android-tools-bin\\\\dist\\\\win32\\\\x86\\\\adb.exe -P 5037 shell getprop ro.product.device\"},\"stderr\":\"error: protocol fault (couldn't read status): connection reset\"}","name":"adb"}
    at PluginIndex.__pluginErrorHandler (C:\Users\lalit\AppData\Local\Temp\26QXuFeDBKOo01Gy82McrKkqlwQ\resources\app.asar\src\core\plugins\index.js:193:11)
    at C:\Users\lalit\AppData\Local\Temp\26QXuFeDBKOo01Gy82McrKkqlwQ\resources\app.asar\src\core\plugins\index.js:151:24
    at C:\Users\lalit\AppData\Local\Temp\26QXuFeDBKOo01Gy82McrKkqlwQ\resources\app.asar.unpacked\node_modules\promise-android-tools\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
