### ISSUE TITLE
OPO installing updates with boot menu superimpressed. Install failed.

### ISSUE THREAD

**Issue by Bonob0b** [ubports/ubports-installer#255]
Dear all,

With installer version 0.1.13-beta, from a PC running ubuntu 16.04, 
sudo ubports-installer
installer running fine.
Phone is rebooting by itself.
but then, on the phone I get the image of the "Installing updates", and one seconde after, I get the boot menu, superimpressed on top of the image of the "Installing updates".
And then nothing happens. 
If I reboot, logo of One plus (powered by android) and that's all.
No ubuntu working.

I tried it on two different OPOs, with the same cable. I changed USBs. Same results.

I tried version 0.1.12 : same results.
It seems that Arthur on telegram had the same problem with a nexus 5.

![photo_2018-05-11_19-28-18](https://user-images.githubusercontent.com/13960214/39997770-4f2548f0-5784-11e8-94a9-cd348b2d6fd9.jpg)

![photo_2018-05-11_19-27-42](https://user-images.githubusercontent.com/13960214/39997747-3ae21508-5784-11e8-9d07-7929dbc52cf0.jpg)

**Comment by Bonob0b** [comment]
And I am also getting 

`debug: adb shell: echo 1
debug:  Error: Command failed: adb -P 5038 shell echo 1
error: device not found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
`Adb and fastboot recognize the device correctly.

**Comment by Bonob0b** [comment]
I tried again today, with 0.1.13-beta, and no surimpressed menu and updates run till the end.
However, OPO is not able to boot (trying to boot and reboot and reboot).

I close this issue
