### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Naturgewalt87** [ubports/ubports-installer#2797]
**UBports Installer `0.9.6-beta` (AppImage)**
Environment: `LinuxMint 5 elsie linux 5.10.0-16-amd64 x64 NodeJS v16.14.2`
Device: [`surya`](https://github.com/ubports/installer-configs/blob/6c4f2e637714d3c1f62d069e0de0e79d9fbaa60f/v2/devices/surya.yml) ([Xiaomi Poco X3 NFC](https://devices.ubuntu-touch.io/device/surya/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"channel":"16.04/arm64/android9/rc"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1660151673066

**Previous Errors:**
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"Invalid sparse file format at header magicFAILED (remote: 'Partition not found')fastboot: error:Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"Invalid sparse file format at header magicFAILED (remote: 'Partition not found')fastboot: error:Command failed"}
    at /tmp/.mount_ubport2mlUL6/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1119:15
    at /tmp/.mount_ubport2mlUL6/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"Invalid sparse file format at header magicFAILED (remote: 'Partition not found')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"Invalid sparse file format at header magicFAILED (remote: 'Partition not found')fastboot: error: Command failed"}
    at /tmp/.mount_ubport2mlUL6/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1119:15
    at /tmp/.mount_ubport2mlUL6/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by luigdima** [comment]
Hello!! same error, you found any solution? thanks!
