### ISSUE TITLE
[Fedora] Appimage installer fails

### ISSUE THREAD

**Issue by peterge1998** [ubports/ubports-installer#2806]
![image](https://user-images.githubusercontent.com/47355238/185353134-ac7d0928-3878-4d51-8a93-2b68a3b569d8.png)
After Downloading all files the installer crashes.
![image](https://user-images.githubusercontent.com/47355238/185353206-02bb5595-5330-47b8-a1cc-49403b31126d.png)

This is the from log (its infinte):
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:198:10)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/plugins/adb/plugin.js:127:27
    at /tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:429:19
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:422:14)
    at Socket.emit (node:events:526:28)
warn: lost connection to device
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at Window.send (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/window.js:46:20)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/prompt.js:35:14
    at new Promise (<anonymous>)
    at prompt (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/prompt.js:33:12)
    at EventEmitter.<anonymous> (/tmp/.mount_ubportkq5siv/resources/app.asar/src/lib/mainEvent.js:269:3)
    at EventEmitter.emit (node:events:526:28)
    at /tmp/.mount_ubportkq5siv/resources/app.asar/src/core/core.js:384:19
    at new Promise (<anonymous>)
```

**Comment by peterge1998** [comment]
![image](https://user-images.githubusercontent.com/47355238/185360238-7ebf704f-c1f2-41b9-ba09-e18c6500eec0.png)
i cant boot into recovery to reconnect, the connections lost message keeps coming up

![image](https://user-images.githubusercontent.com/47355238/185360365-2bb3cc29-08dc-4792-89ff-8ea8af4d45ed.png)

**Comment by amartinz** [comment]
I have dropped `tsparticles` for animating certain steps, which decreases CPU load by a lot.
Additionally, there seems to have been a memory leak with the specific version of `tsparticles` we were using.

https://github.com/ubports/ubports-installer/pull/2809

With this PR applied my CPU usage when animating is below < 10% and the memory leaks are gone.
The javascript vm instance uses < 5 MB.

**Comment by peterge1998** [comment]
was able to install sucessfully after changing data and system to ext4 like shown in this video https://www.youtube.com/watch?v=b4WkjUkHUzw

**Comment by Flohack74** [comment]
@amartinz we need a check in the installer if cache partition is writable before installer pushes files.

**Comment by amartinz** [comment]
Closing this as the original issue was solved and Florian created a new issue to track additional improvements.
