### ISSUE TITLE
Error: systemimage:install: Error: 404

### ISSUE THREAD

**Issue by chr-chr** [ubports/ubports-installer#2870]
Tried to install Ubuntu touch on a Volla Phone

It was flashing, but ended with 404, device bricked :/

The installer better download and check before flashing anything!

**UBports Installer `0.9.7-beta` (AppImage)**
Environment: `Devuan GNU/Linux 3 beowulf linux 5.10.142+ x64 NodeJS v16.15.0`
Device: [`yggdrasilx`](https://github.com/ubports/installer-configs/blob/41ea7e9f76948da347aa285d5d2e9a17f9af9857/v2/devices/yggdrasilx.yml) ([Volla Phone X](https://devices.ubuntu-touch.io/device/yggdrasilx/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":false,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1665782171490

**Previous Errors:**
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/systemimage/api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: core:end: TypeError: Cannot read properties of null (reading 'name')
stack trace: TypeError: Cannot read properties of null (reading 'name')
    at /tmp/.mount_ubportZO9jeE/resources/app.asar/src/core/plugins/core/plugin.js:41:23
```

**Comment by chr-chr** [comment]
Good news:

After _very_ long pressing power key,
device reset somehow in a bootloop but
holding vol up, was able to boot into recovery mode

Then unchecked "flash using fastboot", installer completed.

Also, I used another USB cable
