### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by kaustubhvasagadekar** [ubports/ubports-installer#3021]
**UBports Installer `0.9.7-beta` (exe)**
Environment: `Microsoft Windows 11 Home Single Language 10.0.22621 Windows 10.0.22621 x64 22621 0.0 NodeJS v16.15.0`
Device: [`violet`](https://github.com/ubports/installer-configs/blob/5b999fac996acb85e4a6e2a861744385064840ac/v2/devices/violet.yml) ([Xiaomi Redmi Note 7 Pro](https://devices.ubuntu-touch.io/device/violet/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1673631577413

**Previous Errors:**
```
Error: fastboot:oem_unlock: Error: oem unlock failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\kaust\\AppData\\Local\\Temp\\2ESF6YwUwSZQEc14I55fIb1nr2x\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe oem unlock"},"stderr":"FAILED (remote: 'Token Verify Failed, Reboot the device\r\n')\r\nfastboot: error: Command failed"}
stack trace: Error: oem unlock failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\kaust\\AppData\\Local\\Temp\\2ESF6YwUwSZQEc14I55fIb1nr2x\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe oem unlock"},"stderr":"FAILED (remote: 'Token Verify Failed, Reboot the device\r\n')\r\nfastboot: error: Command failed"}
    at C:\Users\kaust\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar.unpacked\node_modules\promise-android-tools\lib\module.cjs:1367:20
    at C:\Users\kaust\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar.unpacked\node_modules\promise-android-tools\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: fastboot:oem_unlock: Error: oem unlock failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\kaust\\AppData\\Local\\Temp\\2ESF6YwUwSZQEc14I55fIb1nr2x\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe oem unlock"},"stderr":"FAILED (remote: 'Token Verify Failed, Reboot the device\r\n')\r\nfastboot: error: Command failed"}
stack trace: Error: oem unlock failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\kaust\\AppData\\Local\\Temp\\2ESF6YwUwSZQEc14I55fIb1nr2x\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe oem unlock"},"stderr":"FAILED (remote: 'Token Verify Failed, Reboot the device\r\n')\r\nfastboot: error: Command failed"}
    at C:\Users\kaust\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar.unpacked\node_modules\promise-android-tools\lib\module.cjs:1367:20
    at C:\Users\kaust\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar.unpacked\node_modules\promise-android-tools\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kaustubhvasagadekar** [comment]
.
