### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by hansfbaier** [ubports/ubports-installer#3024]
**UBports Installer `0.9.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.15.0-57-generic x64 NodeJS v16.15.0`
Device: [`jasmine_sprout`](https://github.com/ubports/installer-configs/blob/5b999fac996acb85e4a6e2a861744385064840ac/v2/devices/jasmine_sprout.yml) ([Xiaomi Mi A2](https://devices.ubuntu-touch.io/device/jasmine_sprout/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/rc"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1673642693062

Try the install in Indonesia

**Previous Errors:**
```
Error: initialization: Error: {"message":"device offline","name":"adb"}
stack trace: Error: {"message":"device offline","name":"adb"}
    at /snap/ubports-installer/435/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:415:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:81:29
```

**Comment by coffeecatharine** [comment]
did you figure out a way past this?

**Comment by hansfbaier** [comment]
No. I stopped trying
