### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by shivagnihotri** [ubports/ubports-installer#3046]
**UBports Installer `0.9.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 6.0.0-12parrot1-amd64 x64 NodeJS v16.15.0`
Device: [`axolotl`](https://github.com/ubports/installer-configs/blob/8287d36c35b1b1da1532a9800d1941411443c1cd/v2/devices/axolotl.yml) (SHIFT SHIFT6mq)
Target OS: LineageOS
Settings: `{}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1674546060943

Install LineageOS on SHIFT6mq

**Previous Errors:**
```
Error: preparing: TypeError: Cannot read properties of null (reading 'codename')
stack trace: TypeError: Cannot read properties of null (reading 'codename')
    at LineageOSPlugin.remote_values__channels (/snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/lineage_os/plugin.js:99:46)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:97:51
    at async Promise.all (index 0)
```
```
Error: uncaught exception at uncaughtException: TypeError: Cannot read properties of undefined (reading 'condition')
stack trace: TypeError: Cannot read properties of undefined (reading 'condition')
    at Core.step (/snap/ubports-installer/435/app/resources/app.asar/src/core/core.js:330:31)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/core.js:395:56
    at cont (/snap/ubports-installer/435/app/resources/app.asar/src/lib/errors.js:59:35)
    at Timeout._onTimeout (/snap/ubports-installer/435/app/resources/app.asar/src/lib/errors.js:64:15)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```
```
Error: preparing: TypeError: Cannot read properties of null (reading 'codename')
stack trace: TypeError: Cannot read properties of null (reading 'codename')
    at LineageOSPlugin.remote_values__channels (/snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/lineage_os/plugin.js:99:46)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:97:51
    at async Promise.all (index 0)
```
```
Error: uncaught exception at uncaughtException: TypeError: Cannot read properties of undefined (reading 'condition')
stack trace: TypeError: Cannot read properties of undefined (reading 'condition')
    at Core.step (/snap/ubports-installer/435/app/resources/app.asar/src/core/core.js:330:31)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/core.js:395:56
    at cont (/snap/ubports-installer/435/app/resources/app.asar/src/lib/errors.js:59:35)
    at Timeout._onTimeout (/snap/ubports-installer/435/app/resources/app.asar/src/lib/errors.js:64:15)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```
```
Error: preparing: TypeError: Cannot read properties of null (reading 'codename')
stack trace: TypeError: Cannot read properties of null (reading 'codename')
    at LineageOSPlugin.remote_values__channels (/snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/lineage_os/plugin.js:99:46)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:97:51
    at async Promise.all (index 0)
```
```
Error: preparing: TypeError: Cannot read properties of null (reading 'codename')
stack trace: TypeError: Cannot read properties of null (reading 'codename')
    at LineageOSPlugin.remote_values__channels (/snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/lineage_os/plugin.js:99:46)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/index.js:97:51
    at async Promise.all (index 0)
```
```
Error: uncaught exception at uncaughtException: TypeError: Cannot read properties of undefined (reading 'condition')
stack trace: TypeError: Cannot read properties of undefined (reading 'condition')
    at Core.step (/snap/ubports-installer/435/app/resources/app.asar/src/core/core.js:330:31)
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/core.js:395:56
    at cont (/snap/ubports-installer/435/app/resources/app.asar/src/lib/errors.js:59:35)
    at Timeout._onTimeout (/snap/ubports-installer/435/app/resources/app.asar/src/lib/errors.js:64:15)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```

**Comment by PanderMusubi** [comment]
See https://github.com/ubports/ubports-installer/issues/3048 that fixed it fo rme
