### ISSUE TITLE
How to set up a proxy

### ISSUE THREAD

**Issue by sxuniversity** [ubports/ubports-installer#3113]
**UBports Installer `0.9.7-beta` (exe)**
Environment: `Microsoft Windows 11 家庭中文版 10.0.22621 Windows 10.0.22621 x64 22621 0.0 NodeJS v16.15.0`
Device: [`land`](https://github.com/ubports/installer-configs/blob/5454aa5bd274e24ed9d20c1d3a70153ee8738e85/v2/devices/land.yml) ([Xiaomi Redmi 3S 3X 3SP](https://devices.ubuntu-touch.io/device/land/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/hybris/devel"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1676541975773

**Previous Errors:**
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/Ubports-Land/Ubports-CI/raw/master/splash.img Error: getaddrinfo ENOENT raw.githubusercontent.com
stack trace: Error: core:download Error: Error: Download Error: https://github.com/Ubports-Land/Ubports-CI/raw/master/splash.img Error: getaddrinfo ENOENT raw.githubusercontent.com
    at C:\Users\20641\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/Ubports-Land/Ubports-CI/raw/master/splash.img Error: getaddrinfo ENOENT raw.githubusercontent.com
stack trace: Error: core:download Error: Error: Download Error: https://github.com/Ubports-Land/Ubports-CI/raw/master/splash.img Error: getaddrinfo ENOENT raw.githubusercontent.com
    at C:\Users\20641\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by lerignoux** [comment]
I managed to use the installer with a HTTP_PROXY and HTTPS_PROXY on my side, cf MR https://github.com/ubports/ubports-installer/pull/4739
Not sure if it could help
