### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by lentas1** [ubports/ubports-installer#3137]
**UBports Installer `0.9.7-beta` (exe)**
Environment: `Microsoft Windows 11 Home 10.0.22621 Windows 10.0.22621 x64 22621 0.0 NodeJS v16.15.0`
Device: [`herolte`](https://github.com/ubports/installer-configs/blob/5454aa5bd274e24ed9d20c1d3a70153ee8738e85/v2/devices/herolte.yml) ([Samsung Galaxy S7 Exynos](https://devices.ubuntu-touch.io/device/herolte/))
Target OS: Ubuntu Touch
Settings: `{"channel":"20.04/arm64/android9plus/devel"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1677420274396

My s7 doesnt install

**Previous Errors:**
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__flash')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__flash')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\index.js:81:29
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\systemimage\api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: core:end: TypeError: Cannot read properties of null (reading 'name')
stack trace: TypeError: Cannot read properties of null (reading 'name')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\core\plugin.js:41:23
```
```
Error: plugin wait(): Error: {"message":"{\"error\":{\"code\":1,\"cmd\":\"C:\\\\Users\\\\lenni\\\\AppData\\\\Local\\\\Temp\\\\2ESF6YwUwSZQEc14I55fIb1nr2x\\\\resources\\\\app.asar.unpacked\\\\node_modules\\\\android-tools-bin\\\\dist\\\\win32\\\\x86\\\\adb.exe -P 5037 shell getprop ro.product.device\"},\"stderr\":\"error: closed\"}","name":"adb"}
stack trace: Error: {"message":"{\"error\":{\"code\":1,\"cmd\":\"C:\\\\Users\\\\lenni\\\\AppData\\\\Local\\\\Temp\\\\2ESF6YwUwSZQEc14I55fIb1nr2x\\\\resources\\\\app.asar.unpacked\\\\node_modules\\\\android-tools-bin\\\\dist\\\\win32\\\\x86\\\\adb.exe -P 5037 shell getprop ro.product.device\"},\"stderr\":\"error: closed\"}","name":"adb"}
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar.unpacked\node_modules\promise-android-tools\lib\module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:415:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__flash')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__flash')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\index.js:81:29
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\index.js:81:29
```
```
Error: systemimage:install: Error: 404
stack trace: Error: 404
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\systemimage\api.js:47:13
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
Error: unknown: TypeError: Cannot read properties of undefined (reading 'action__wait')
stack trace: TypeError: Cannot read properties of undefined (reading 'action__wait')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\index.js:81:29
```
```
Error: core:end: TypeError: Cannot read properties of null (reading 'name')
stack trace: TypeError: Cannot read properties of null (reading 'name')
    at C:\Users\lenni\AppData\Local\Temp\2ESF6YwUwSZQEc14I55fIb1nr2x\resources\app.asar\src\core\plugins\core\plugin.js:41:23
```

**Comment by lentas1** [comment]
now cant push the update file to device
