### ISSUE TITLE
unhandled rejection at [object Promise]

### ISSUE THREAD

**Issue by logicprobe** [ubports/ubports-installer#3250]
**UBports Installer `0.9.7-beta` (deb)**
Environment: `Pop 22.04 LTS jammy linux 6.2.6-76060206-generic x64 NodeJS v16.15.0`
Device: [`sargo`](https://github.com/ubports/installer-configs/blob/fb03a5d243db179fe65fabe3bb5da8c1f26eb411/v2/devices/sargo.yml) ([Google Pixel 3a/3a XL](https://devices.ubuntu-touch.io/device/sargo/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/devel"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1682519535378

run ubports-installer.  error occurs at the very end.

info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
error: Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: Hostname/IP does not match certificate's altnames: Host: ubports.open-cuts.org. is not in the cert's altnames: DNS:*.showbet.work, DNS:showbet.work
stack trace: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: Hostname/IP does not match certificate's altnames: Host: ubports.open-cuts.org. is not in the cert's altnames: DNS:*.showbet.work, DNS:showbet.work
    at /opt/ubports-installer/resources/app.asar/node_modules/open-cuts-reporter/lib/module.cjs:111:15
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:39180) UnhandledPromiseRejectionWarning: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: Hostname/IP does not match certificate's altnames: Host: ubports.open-cuts.org. is not in the cert's altnames: DNS:*.showbet.work, DNS:showbet.work
    at /opt/ubports-installer/resources/app.asar/node_modules/open-cuts-reporter/lib/module.cjs:111:15
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `ubports-installer.bin --trace-warnings ...` to show where the warning was created)
(node:39180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Unknown Error

**Comment by prophanetes** [comment]
Confirmed. Got this error yesterday and again today.

**Comment by prophanetes** [comment]
Got the same error again just now.
