### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by tvny75** [ubports/ubports-installer#3283]
**UBports Installer `0.10.0` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19045 Windows 10.0.19045 x64 19045 0.0 NodeJS v18.12.1`
Device: [`X00TD`](https://github.com/ubports/installer-configs/blob/1d19c096d0f6a5cda77073bebf342ba9985f457c/v2/devices/X00TD.yml) ([Asus Zenfone Max Pro M1](https://devices.ubuntu-touch.io/device/X00TD/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":false,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1684067602250

**Previous Errors:**
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\ZAQWSX~1\\AppData\\Local\\Temp\\2OtAFsnV2Em3s1DrbrINBarrFLV\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe format:ext4 vendor"},"stderr":"FAILED (remote: 'GetVar Variable Not found')\r\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\ZAQWSX~1\\AppData\\Local\\Temp\\2OtAFsnV2Em3s1DrbrINBarrFLV\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe format:ext4 vendor"},"stderr":"FAILED (remote: 'GetVar Variable Not found')\r\nfastboot: error: Command failed"}
    at C:\Users\ZAQWSX~1\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar.unpacked\node_modules\promise-android-tools\lib\module.cjs:1250:15
    at C:\Users\ZAQWSX~1\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar.unpacked\node_modules\promise-android-tools\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by tvny75** [comment]
Finally, I installed Ubuntu Touch Successfully, after formatting manually using twrp. Thanks
