### ISSUE TITLE
Boot to the MI Recovery

### ISSUE THREAD

**Issue by heychinje** [ubports/ubports-installer#3328]
**UBports Installer `0.10.0` (dmg)**
Environment: `macOS 12.6.5 macOS Monterey darwin 21.6.0 x64 21G531 NodeJS v18.12.1`
Device: [`dipper`](https://github.com/ubports/installer-configs/blob/7274edfc7047e051af271d0a2dd042b1db893993/v2/devices/dipper.yml) ([Xiaomi Mi 8](https://devices.ubuntu-touch.io/device/dipper/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/devel"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1686402680392

1. Step by step; 2. At the last step, it should boot to ubuntu touch OS, but it boots to the Mi Recovery

**Previous Errors:**
```
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Permission denied"}
stack trace: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Permission denied"}
    at /Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
```
```
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Permission denied"}
stack trace: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Permission denied"}
    at /Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
```

**Comment by heychinje** [comment]
Btw, I found an issue that the MI-Recovery 3.0 still cannot be replaced on MI 8 (dipper) devices. Maybe it causes permission denied.
