### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by pestryy** [ubports/ubports-installer#3344]
**UBports Installer `0.10.0` (deb)**
Environment: `Ubuntu 22.04.2 LTS Jammy Jellyfish linux 5.19.0-45-generic x64 NodeJS v18.12.1`
Device: [`dipper`](https://github.com/ubports/installer-configs/blob/72fa82d37b0fea1465b12a1bdda9c437c7e228fe/v2/devices/dipper.yml) ([Xiaomi Mi 8](https://devices.ubuntu-touch.io/device/dipper/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/devel"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1687556872265

touch install and after reboot to fastboot my device over 1-2 seconds  exit from foastboot and i dont see in my Pc over fastboot devices my phone mi8

**Previous Errors:**
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"FAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"FAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 cache"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 cache"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by pestryy** [comment]
![image](https://github.com/ubports/ubports-installer/assets/10463506/d203cdd8-5aee-40aa-a757-2008988d3df9)
recycle formatting

**Comment by pestryy** [comment]
My environment data:
$ cat /etc/*-release | grep PRETTY
PRETTY_NAME="Ubuntu 22.04.2 LTS"
$ ubports-installer --version
0.10.0
$ adb --version
Android Debug Bridge version 1.0.41
Version 28.0.2-debian
$ fastboot --version
fastboot version 28.0.2-debian
Connecting the phone to the computer:

$ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
26a80c15        device
I reload into the bootloader:
$ adb reboot bootloader
It's OK:
$ fastboot devices
26a80c15        fastboot

Start ubports-installer:
$ ubports-installer 
info: Welcome to the UBports Installer version 0.10.0!
info: device detected: dipper
I see a banner:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/182eb96a-6eb5-4c93-8be9-83d1f9ba9ca5)
Then:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/a2a195df-3911-4cad-851b-8aa7a8708ba7)
Then:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/bb33d73a-a416-4c80-98cd-425d519eaca4)
Then:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/909f3d48-eab5-4d61-a339-43fdde8071bb)

**Comment by pestryy** [comment]
```
My environment data:
$ cat /etc/*-release | grep PRETTY
PRETTY_NAME="Ubuntu 22.04.2 LTS"
$ ubports-installer --version
0.10.0
$ adb --version
Android Debug Bridge version 1.0.41
Version 28.0.2-debian
$ fastboot --version
fastboot version 28.0.2-debian
Connecting the phone to the computer:

$ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
26a80c15        device
I reload into the bootloader:
$ adb reboot bootloader
It's OK:
$ fastboot devices
26a80c15        fastboot
```

Start ubports-installer:
```
$ ubports-installer 
info: Welcome to the UBports Installer version 0.10.0!
info: device detected: dipper
```
I see a banner:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/182eb96a-6eb5-4c93-8be9-83d1f9ba9ca5)
Then:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/a2a195df-3911-4cad-851b-8aa7a8708ba7)
Then:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/bb33d73a-a416-4c80-98cd-425d519eaca4)
Then:
![image](https://github.com/ubports-dipper/xiaomi-dipper/assets/10463506/909f3d48-eab5-4d61-a339-43fdde8071bb)

**Comment by pestryy** [comment]
![image](https://github.com/ubports/ubports-installer/assets/10463506/12b56aa0-e239-4e03-b118-04ab1aa8b683)
