### ISSUE TITLE
The download failed every time!!!

### ISSUE THREAD

**Issue by xc1984759471** [ubports/ubports-installer#3407]
**UBports Installer `0.10.0` (exe)**
Environment: `Microsoft Windows 11 专业版 10.0.22621 Windows 10.0.22621 x64 22621 0.0 NodeJS v18.12.1`
Device: [`violet`](https://github.com/ubports/installer-configs/blob/b750ffb887886c7cf6e9757a4426409c316fe29c/v2/devices/violet.yml) ([Xiaomi Redmi Note 7 Pro](https://devices.ubuntu-touch.io/device/violet/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/rc"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1690885105353

**Previous Errors:**
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/dtbo.img Error: read ECONNRESET
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/dtbo.img Error: read ECONNRESET
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vendor.zip Error: connect ETIMEDOUT 20.205.243.166:443
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vendor.zip Error: connect ETIMEDOUT 20.205.243.166:443
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/dtbo.img Error: connect ETIMEDOUT 20.205.243.166:443
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/dtbo.img Error: connect ETIMEDOUT 20.205.243.166:443
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vendor.zip Error: connect ETIMEDOUT 20.205.243.166:443
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vendor.zip Error: connect ETIMEDOUT 20.205.243.166:443
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/modem.img Error: connect ETIMEDOUT 20.205.243.166:443
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/modem.img Error: connect ETIMEDOUT 20.205.243.166:443
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/modem.img Error: connect ETIMEDOUT 20.205.243.166:443
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/modem.img Error: connect ETIMEDOUT 20.205.243.166:443
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: core:download: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vbmeta.img Error: connect ETIMEDOUT 20.205.243.166:443
stack trace: Error: core:download Error: Error: Download Error: https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vbmeta.img Error: connect ETIMEDOUT 20.205.243.166:443
    at C:\Users\ab152\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar\src\core\plugins\core\plugin.js:168:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by xc1984759471** [comment]
The download speed is fast, but every time you download for a while, especially when you download the next file, you will suddenly pop up a download failure message, almost every time
