### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by impsinha** [ubports/ubports-installer#3426]
**UBports Installer `0.10.0` (deb)**
Environment: `Ubuntu 22.04.3 LTS Jammy Jellyfish linux 6.2.0-26-generic x64 NodeJS v18.12.1`
Device: [`beryllium`](https://github.com/ubports/installer-configs/blob/b750ffb887886c7cf6e9757a4426409c316fe29c/v2/devices/beryllium.yml) ([Xiaomi Poco F1](https://devices.ubuntu-touch.io/device/beryllium/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1691787654587

**Previous Errors:**
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (Protocol error))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (Protocol error))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:format: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
stack trace: Error: formatting failed: Error: {"error":{"code":1,"cmd":"fastboot format:ext4 system"},"stderr":"< waiting for any device >\nFAILED (Write to device failed (No such device))\nfastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1250:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by impsinha** [comment]
Using usb hub solved the issue
