### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by barafael** [ubports/ubports-installer#3442]
**UBports Installer `0.10.0` (AppImage)**
Environment: `ManjaroLinux 23.0.0 Uranos linux 5.15.125-1-MANJARO x64 rolling NodeJS v18.12.1`
Device: [`vidofnir`](https://github.com/ubports/installer-configs/blob/ee844058cd08f109dc2f4e7efe2d517559d1630c/v2/devices/vidofnir.yml) ([Volla Phone X23](https://devices.ubuntu-touch.io/device/vidofnir/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1692482948848

**Previous Errors:**
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:set_active: Error: failed to set active slot: Error: {"error":{"code":1,"cmd":"fastboot --set-active=a"},"stderr":"Setting current slot to 'a'                        FAILED (remote: 'set_active command is not allowed on locked devices')\nfastboot: error: Command failed"}
stack trace: Error: failed to set active slot: Error: {"error":{"code":1,"cmd":"fastboot --set-active=a"},"stderr":"Setting current slot to 'a'                        FAILED (remote: 'set_active command is not allowed on locked devices')\nfastboot: error: Command failed"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1283:15
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Permission denied"}
stack trace: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Permission denied"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
```
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"fastboot: error: Command failed"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'No support by lock control')fastboot: error: Command failed"}
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_ubporthItqan/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I cannot really give more detail as the info in the error message popup is not copyable. If necessary I can reproduce and type letter by letter. It should really be copyable.

About the phone, it still has stock Volla OS, and holding vol-up/vol-down then power does not seem to have any effect. The only time when I see fastboot and recovery mode are when restarting during installation using ubports, which does fail pretty early.

**Comment by Patrick762** [comment]
Seems like you have to unlock the bootloader yourself:
https://source.android.com/docs/core/architecture/bootloader/locking_unlocking?hl=de#unlocking-bootloader

That fixed it for me
