### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\Florian\AppData\Roaming\ubports\pool\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-installer#346]
```
{"level":"info","message":"Start pushing 13 files","timestamp":"2018-07-02T20:32:44.714Z"}
{"message":"Command failed: adb -P 5038 push 'C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz' /cache/recovery/\ncannot stat ''C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz'': No such file or directory\r\n","stack":"Error: Command failed: adb -P 5038 push 'C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz' /cache/recovery/\ncannot stat ''C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz'': No such file or directory\r\n\n    at ChildProcess.exithandler (child_process.js:282:12)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at maybeClose (internal/child_process.js:921:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)","killed":false,"code":1,"signal":null,"cmd":"adb -P 5038 push 'C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz' /cache/recovery/","level":"debug","timestamp":"2018-07-02T20:32:45.373Z"}
{"level":"error","message":"Devices: Error: Adb push error: cannot stat ''C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz'': No such file or directory\r\n","timestamp":"2018-07-02T20:32:45.379Z"}
{"level":"error","message":"Devices: Adb push error: cannot stat ''C:\\Users\\Florian\\AppData\\Roaming\\ubports\\pool\\ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz'': No such file or directory\r\n","timestamp":"2018-07-02T20:32:45.379Z"}
{"message":"Command failed: adb -P 5038 shell stat -t /cache/recovery//ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz |awk '{print $2}'\nDer Befehl \"awk\" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n","stack":"Error: Command failed: adb -P 5038 shell stat -t /cache/recovery//ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz |awk '{print $2}'\nDer Befehl \"awk\" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n\n    at ChildProcess.exithandler (child_process.js:282:12)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at maybeClose (internal/child_process.js:921:16)\n    at Socket.stream.socket.on (internal/child_process.js:348:11)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at Pipe._handle.close [as _onclose] (net.js:549:12)","killed":false,"code":255,"signal":null,"cmd":"adb -P 5038 shell stat -t /cache/recovery//ubports-9517a9987bb21f29e7ccd944aa4b3859d19f2763a8cbe7b90b87bdf9c3dee80c.tar.xz |awk '{print $2}'","level":"debug","timestamp":"2018-07-02T20:32:46.801Z"}
{"level":"info","message":"ADB push 0%","timestamp":"2018-07-02T20:32:46.801Z"}
```

Also the command awk is not available in Windows...

**Comment by Flohack74** [comment]
Needless to say, all files are in the right place:
![grafik](https://user-images.githubusercontent.com/16186470/42185477-550f8294-7e49-11e8-9b72-8896b5472f84.png)
