### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by gwicho38** [ubports/ubports-installer#3494]
**UBports Installer `0.9.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 6.4.8-100.fc37.x86_64 x64 NodeJS v16.15.0`
Device: `FP4`
Target OS: undefined
Settings: `{}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1696085105143

**Previous Errors:**
```
Error: preparing: TypeError: Cannot read properties of undefined (reading 'interfaces')
stack trace: TypeError: Cannot read properties of undefined (reading 'interfaces')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/postmarketos/api.js:42:9
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
```
```
Error: postmarketos:download: TypeError: Cannot read properties of undefined (reading 'devices')
stack trace: TypeError: Cannot read properties of undefined (reading 'devices')
    at /snap/ubports-installer/435/app/resources/app.asar/src/core/plugins/postmarketos/api.js:68:23
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by coffeecatharine** [comment]
did you figure out a way past this?

**Comment by gwicho38** [comment]
> did you figure out a way past this?

Hi, thanks for the follow up. Yes. Solution was to upgrade to 0.10 and reinstall Android 11.
