### ISSUE TITLE
System Image Upgrader error

### ISSUE THREAD

**Issue by VictorWesterlund** [ubports/ubports-installer#3508]
**UBports Installer `0.10.0` (exe)**
Environment: `Microsoft Windows 11 Pro 10.0.22621 Windows 10.0.22621 x64 22621 0.0 NodeJS v18.12.1`
Device: [`FP4`](https://github.com/ubports/installer-configs/blob/120be2cd71613ca217f71a60a909597cd4064c82/v2/devices/FP4.yml) ([Fairphone 4](https://devices.ubuntu-touch.io/device/FP4/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"partition":true,"channel":"20.04/arm64/android9plus/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1697398656719

## Additional infomation

UBports installer gets stuck on "booting to fastbootd" - even after ubports fastbootd opened on the device. Going back to the bootloader on the device causes the ubports desktop app to push broken Ubuntu Touch files to the device, making it boot into recovery mode

## From System Image Upgrader for Ubuntu Touch
```
Formatting: system
system partition: /dev/block/dm-0
/dev/block/dm-0
umount: /system_root: No such file or directory
umount: /mnt/system: Invalid argument
mke2fs: 1.45.4 (23-Sep-2019)
mkfs.ext4: invalid blocks '/dev/block/dm-1' on device '/dev/block/dm-0'
```

## From UBports installer on Windows

**Previous Errors:**
```
Error: fastboot:delete_logical_partition: Error: deleting logical partition failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\victo\\AppData\\Local\\Temp\\2OtAFsnV2Em3s1DrbrINBarrFLV\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe delete-logical-partition system_ext_a"},"stderr":"Deleting 'system_ext_a'                            FAILED (remote: 'unknown command')\r\nfastboot: error: Command failed"}
stack trace: Error: deleting logical partition failed: Error: {"error":{"code":1,"cmd":"C:\\Users\\victo\\AppData\\Local\\Temp\\2OtAFsnV2Em3s1DrbrINBarrFLV\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe delete-logical-partition system_ext_a"},"stderr":"Deleting 'system_ext_a'                            FAILED (remote: 'unknown command')\r\nfastboot: error: Command failed"}
    at C:\Users\victo\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar.unpacked\node_modules\promise-android-tools\lib\module.cjs:1314:15
    at C:\Users\victo\AppData\Local\Temp\2OtAFsnV2Em3s1DrbrINBarrFLV\resources\app.asar.unpacked\node_modules\promise-android-tools\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by VictorWesterlund** [comment]
Solved by reflashing Fairphone OS and then running the installer again.
