### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by henryhkb** [ubports/ubports-installer#3554]
**UBports Installer `0.10.0` (deb)**
Environment: `Ubuntu 23.10 Mantic Minotaur linux 6.5.0-10-generic x64 NodeJS v18.12.1`
Device: [`trltetmo`](https://github.com/ubports/installer-configs/blob/120be2cd71613ca217f71a60a909597cd4064c82/v2/devices/trltetmo.yml) ([Samsung Galaxy Note 4 [910T]](https://devices.ubuntu-touch.io/device/trltetmo/))
Target OS: Ubuntu Touch
Settings: `{"wipe":true,"channel":"16.04/armhf/hybris/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1700383986905

**Previous Errors:**
```
Error: heimdall:flash: Error: {"error":{"code":1,"cmd":"heimdall flash --BOOT /home/wassabi/.cache/ubports/trltetmo/firmware/halium-unlocked-recovery_trltetmo.img --RECOVERY /home/wassabi/.cache/ubports/trltetmo/firmware/halium-unlocked-recovery_trltetmo.img"},"stdout":"Heimdall v1.4.2\n\nCopyright (c) 2010-2017 Benjamin Dobell, Glass Echidna\nhttp://www.glassechidna.com.au/\n\nThis software is provided free of charge. Copying and redistribution is\nencouraged.\n\nIf you appreciate this software and you would like to support future\ndevelopment please consider donating:\nhttp://www.glassechidna.com.au/donate/\n\nInitialising connection...\nDetecting device...\nClaiming interface...\nSetting up interface...\n\nInitialising protocol...\nProtocol initialisation successful.\n\nBeginning session...\n\nSome devices may take up to 2 minutes to respond.\nPlease be patient!\n\nSession begun.\n\nDownloading device's PIT file...\nPIT file download successful.\n\nUploading BOOT\n0%\b\b6%\b\b12%\b\b\b18%\b\b\b24%\b\b\b30%\b\b\b36%\b\b\b42%\b\b\b48%\b\b\b54%\b\b\b60%\b\b\b67%\b\b\b73%\b\b\b79%\b\b\b85%\b\b\b91%\b\b\b97%\b\b\b100%Ending session...\nRebooting device...\nReleasing device interface...","stderr":"ERROR: Failed to confirm end of file transfer sequence!\nERROR: BOOT upload failed!"}
stack trace: Error: {"error":{"code":1,"cmd":"heimdall flash --BOOT /home/wassabi/.cache/ubports/trltetmo/firmware/halium-unlocked-recovery_trltetmo.img --RECOVERY /home/wassabi/.cache/ubports/trltetmo/firmware/halium-unlocked-recovery_trltetmo.img"},"stdout":"Heimdall v1.4.2\n\nCopyright (c) 2010-2017 Benjamin Dobell, Glass Echidna\nhttp://www.glassechidna.com.au/\n\nThis software is provided free of charge. Copying and redistribution is\nencouraged.\n\nIf you appreciate this software and you would like to support future\ndevelopment please consider donating:\nhttp://www.glassechidna.com.au/donate/\n\nInitialising connection...\nDetecting device...\nClaiming interface...\nSetting up interface...\n\nInitialising protocol...\nProtocol initialisation successful.\n\nBeginning session...\n\nSome devices may take up to 2 minutes to respond.\nPlease be patient!\n\nSession begun.\n\nDownloading device's PIT file...\nPIT file download successful.\n\nUploading BOOT\n0%\b\b6%\b\b12%\b\b\b18%\b\b\b24%\b\b\b30%\b\b\b36%\b\b\b42%\b\b\b48%\b\b\b54%\b\b\b60%\b\b\b67%\b\b\b73%\b\b\b79%\b\b\b85%\b\b\b91%\b\b\b97%\b\b\b100%Ending session...\nRebooting device...\nReleasing device interface...","stderr":"ERROR: Failed to confirm end of file transfer sequence!\nERROR: BOOT upload failed!"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
```
```
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: closed"}
stack trace: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: closed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:117:20
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
```

**Comment by henryhkb** [comment]
done
