### ISSUE TITLE
The screen of OEM unlock disturbs the boot into fastbootd mode.

### ISSUE THREAD

**Issue by dogematti** [ubports/ubports-installer#3735]
**UBports Installer `0.10.0` (dmg)**
Environment: `macOS 14.4 macOS darwin 23.4.0 x64 23E214 NodeJS v18.12.1`
Device: [`FP4`](https://github.com/ubports/installer-configs/blob/4863a0155c39db6c425e168bfe5d8196e939c6da/v2/devices/FP4.yml) ([Fairphone 4](https://devices.ubuntu-touch.io/device/FP4/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"partition":true,"wipe":true,"channel":"20.04/arm64/android9plus/rc"}`
OPEN-CUTS run: *N/A* 
Pastebin: *N/A* 

Make the timeout for waiting for fastbootd larger.

**Previous Errors:**
```
Error: fastboot:erase: Error: erasing failed: Error: {"error":{"code":1,"cmd":"fastboot erase userdata"},"stderr":"ERROR: could not clear input pipe; result e00002ed, ignoring...\nERROR: could not clear output pipe; result e00002ed, ignoring....\nERROR: usb_write failed with status e00002ed\nERROR: usb_write failed with status e000404f\nErasing 'userdata'                                 ERROR: usb_write failed with status e000404f\nFAILED (Write to device failed (No such file or directory))\nfastboot: error: Command failed"}
stack trace: Error: erasing failed: Error: {"error":{"code":1,"cmd":"fastboot erase userdata"},"stderr":"ERROR: could not clear input pipe; result e00002ed, ignoring...\nERROR: could not clear output pipe; result e00002ed, ignoring....\nERROR: usb_write failed with status e00002ed\nERROR: usb_write failed with status e000404f\nErasing 'userdata'                                 ERROR: usb_write failed with status e000404f\nFAILED (Write to device failed (No such file or directory))\nfastboot: error: Command failed"}
    at /Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1265:15
    at /Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by dogematti** [comment]
The warning screen makes everything wonky...

**Comment by dogematti** [comment]
Succesfull install though.
