### ISSUE TITLE
Trying to upgrade Poco X3 NFC.

### ISSUE THREAD

**Issue by chemarito** [ubports/ubports-installer#3738]
**UBports Installer `0.10.0` (AppImage)**
Environment: `LMDE 6 faye linux 6.1.0-18-amd64 x64 NodeJS v18.12.1`
Device: [`surya`](https://github.com/ubports/installer-configs/blob/4863a0155c39db6c425e168bfe5d8196e939c6da/v2/devices/surya.yml) ([Xiaomi Poco X3 NFC](https://devices.ubuntu-touch.io/device/surya/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: *N/A*

**Comment by chemarito** [comment]
info: Welcome to the UBports Installer version 0.10.0!
info: device detected: surya
info: Installing Ubuntu Touch on your Xiaomi Poco X3 NFC (surya)
info: configuring...
info: settings: {"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/stable"}
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
    at /tmp/.mount_gearleINPvCW/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_gearleINPvCW/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
warn: restart after error
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
    at /tmp/.mount_gearleINPvCW/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /tmp/.mount_gearleINPvCW/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
warn: error ignored
info: Downloading 14 files
info: Downloaded file 1 of 14
info: Downloaded file 2 of 14
info: Downloaded file 3 of 14
info: Downloaded file 4 of 14
info: Downloaded file 5 of 14
info: Downloaded file 6 of 14
info: Downloaded file 7 of 14
info: Downloaded file 8 of 14
info: Downloaded file 9 of 14
info: Downloaded file 10 of 14
info: Downloaded file 11 of 14
info: Downloaded file 12 of 14
info: Downloaded file 13 of 14
info: Downloaded file 14 of 14
info: UBports Installer restarting...
info: device detected: surya
info: Installing Ubuntu Touch on your Xiaomi Poco X3 NFC (surya)
info: configuring...
info: settings: {"bootstrap":true,"channel":"20.04/arm64/android9plus/stable"}

**Comment by chemarito** [comment]
No, the device is broken, I was unable to repair it. I'll try in a future.
