### ISSUE TITLE
XIAOMI POCO X3 INSTALLATION  OF UBUNTU TOUCH 20.04  OS FAILURE.

### ISSUE THREAD

**Issue by ahalyachinnasamy1967** [ubports/ubports-installer#3869]
**UBports Installer `0.10.0` (snap)**
Environment: `Ubuntu Core 20 linux 6.8.0-45-generic x64 NodeJS v18.12.1`
Device: [`surya`](https://github.com/ubports/installer-configs/blob/316a4834ca878e458f9ab1a26cfdd7a58d14ad1e/v2/devices/surya.yml) ([Xiaomi Poco X3 NFC](https://devices.ubuntu-touch.io/device/surya/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"channel":"20.04/arm64/android9plus/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: *N/A* 

**Previous Errors:**
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
    at /snap/ubports-installer/462/app/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /snap/ubports-installer/462/app/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ds2k5** [comment]
Had the simluar issue then I found this

https://github.com/ubuntu-touch-surya/ubuntu-touch-surya/blob/master/FIRMWARE.md


But the Link is dead.
But you can search Poco X3 fastboot rom .tgz

Select a Version 12.0.x 

Flash it to the Device

Redu the Bootloader Unlock.

Then retry to Flash with Ubport-installer.

Good luck hope helped you

**Comment by mincaeuro** [comment]
did you solved it ?

**Comment by ds2k5** [comment]
@mincaeuro 

did you ask @ds2k5  or @ahalyachinnasamy1967
