### ISSUE TITLE
(surya) Xiaomi Poco X3 NFC - The System has been destroyed | Partition not found

### ISSUE THREAD

**Issue by ds2k5** [ubports/ubports-installer#3875]
**UBports Installer `0.10.0` (deb)**
Environment: `Debian GNU/Linux 12 bookworm linux 6.1.0-26-amd64 x64 NodeJS v18.12.1`
Device: [`surya`](https://github.com/ubports/installer-configs/blob/72d2692be666cfeaebac46ce487c985725d96f0a/v2/devices/surya.yml) ([Xiaomi Poco X3 NFC](https://devices.ubuntu-touch.io/device/surya/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"channel":"20.04/arm64/android9plus/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: *N/A* 

**Previous Errors:**
```
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"FAILED (remote: 'Partition not found')fastboot: error: Command failed"}
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/lib/module.cjs:1121:15
    at /opt/ubports-installer/resources/app.asar.unpacked/node_modules/promise-android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Environment: Debian 12.7 / bookworm x86_64

MUI 14.0.5  /  Android Version 12 SKQ1.211019.001 

UBports Installer version 0.10.0

![grafik](https://github.com/user-attachments/assets/c1df4793-cee4-4579-9db8-5cfe3c8f1fd5)

![grafik](https://github.com/user-attachments/assets/9fca1b92-b719-494d-826e-e02a858c53e0)

![grafik](https://github.com/user-attachments/assets/5fa86c66-1753-4580-b450-51775c925462)

![grafik](https://github.com/user-attachments/assets/cc05eaf3-eed4-4574-b711-318f0e31efff)

Got this on the Display of the SmartPhone

![grafik](https://github.com/user-attachments/assets/fc6fa9a8-6841-4d98-9cd3-6ad5744d3fdb)

![grafik](https://github.com/user-attachments/assets/74dd72e8-1673-429f-8a76-55aef9463506)

![grafik](https://github.com/user-attachments/assets/72b1019d-7ca9-470f-88b8-d097a7be364f)

![grafik](https://github.com/user-attachments/assets/ff463a85-159f-44a7-831b-d323a38a74db)

How to fix this ?

**Comment by ds2k5** [comment]
Solution was to Flash Image with Android 10 to the Device first.

fastboot rom  .tgz
