### ISSUE TITLE
Error when trying to flash 16.04/rc to 'frieza' bq m10 fhd

### ISSUE THREAD

**Issue by uududde** [ubports/ubports-installer#391]
Hi there,

I just signed up due to an error when trying to install the 16.04/rc on my bq m10 fhd via the snap ubports-installer which was installed only moments before so it should be the latest version: ubports-installer  0.1.20-beta from »mariogrip« installed.

Here is the output of the console after starting the snap

    $ ubports-installer 
    Pug interceptor registered successfully
    debug: Welcome to the party
    debug: Killing all running adb servers...
    debug: Using native platform tools!
    debug: Running platform tool exec cmd adb kill-server
    debug: 
    debug: Running platform tool exec cmd adb -P 5038 kill-server
    debug: 
    debug: adb shell: echo 1
    debug: Running platform tool exec cmd adb -P 5038 shell echo 1
    debug: Successfully downloaded devices list
    warn: Running latest stable version.
    debug: 
    debug: adb shell: getprop ro.product.device
    debug: Running platform tool exec cmd adb -P 5038 shell getprop ro.product.device
    debug: 
    debug: getprop: frieza
    debug: adb shell: cat /etc/system-image/channel.ini
    debug: Running platform tool exec cmd adb -P 5038 shell cat /etc/system-image/channel.ini
    debug: 
    debug: adb shell: echo 1
    debug: Running platform tool exec cmd adb -P 5038 shell echo 1
    debug: 
    debug: reboot to bootloader
    debug: Running platform tool exec cmd adb -P 5038 reboot bootloader
    debug: 
    debug: reboot to bootloader [DONE] err:null
    debug: checking password
    debug: correct password
    debug: fastboot: wait for device
    info: Download startCheck
    info: checked: recovery-frieza.img
    info: /home/udoo/.cache/ubports/images/frieza/recovery-frieza.img already exists with the expected checksum, so download will be skipped
    info: Download complete
    info: done downloading(once listener)
    debug: fastboot: flash; [{"type":"recovery","url":"http://cdimage.ubports.com/devices/recovery-frieza.img","checksum":"374f184e2675f53651cf4790ee685ee363f59f2be98ea99a6d9d948bbc168c8b","path":"/home/udoo/.cache/ubports/images/frieza"}]
    info: Booting into recovery image...
    info: bootstrap done
    debug: adb shell: echo 1
    debug: Running platform tool exec cmd adb -P 5038 shell echo 1
    debug:  message=Command failed: adb -P 5038 shell echo 1
    error: no devices/emulators found
    , stack=Error: Command failed: adb -P 5038 shell echo 1
    error: no devices/emulators found
    
    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=1, signal=null, cmd=adb -P 5038 shell echo 1
    debug: adb shell: echo 1
    debug: Running platform tool exec cmd adb -P 5038 shell echo 1
    debug:  message=Command failed: adb -P 5038 shell echo 1
    error: no devices/emulators found
    , stack=Error: Command failed: adb -P 5038 shell echo 1
    error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=1, signal=null, cmd=adb -P 5038 shell echo 1
    debug: adb shell: echo 1
    debug: Running platform tool exec cmd adb -P 5038 shell echo 1
    debug:  message=Command failed: adb -P 5038 shell echo 1
    error: no devices/emulators found
    , stack=Error: Command failed: adb -P 5038 shell echo 1
    error: no devices/emulators found
    
    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=1, signal=null, cmd=adb -P 5038 shell echo 1
    debug: adb shell: echo 1
    debug: Running platform tool exec cmd adb -P 5038 shell echo 1
    debug: 
    info: Download startCheck
    debug:  url=https://system-image.ubports.com//pool/ubports-074647d5912a2423537abc8874438dc53d59a5a6b7887cb02eac0f6a28ef7169.tar.xz, path=/home/udoo/.cache/ubports/pool, checksum=34f86d9349d359460d9f3ba4145aa791c95336a2942bc39c8351b5604775c4cf, url=https://system-image.ubports.com//pool/ubports-074647d5912a2423537abc8874438dc53d59a5a6b7887cb02eac0f6a28ef7169.tar.xz.asc, path=/home/udoo/.cache/ubports/pool, url=https://system-image.ubports.com//pool/device-2ca0785269f85a0f7480633ad9adbe72f8b4020df6a10657eb23cd6abe601481.tar.xz, path=/home/udoo/.cache/ubports/pool, checksum=e2eabad545fe59063e41dcb84271b9b774544d63003e4f8b02e41485486ccc90, url=https://system-image.ubports.com//pool/device-2ca0785269f85a0f7480633ad9adbe72f8b4020df6a10657eb23cd6abe601481.tar.xz.asc, path=/home/udoo/.cache/ubports/pool, url=https://system-image.ubports.com//pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz, path=/home/udoo/.cache/ubports/pool, checksum=5b6e870acf8944330acb2a9dad6f5270bd06c377603a3115f805290e989ab421, url=https://system-image.ubports.com//pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc, path=/home/udoo/.cache/ubports/pool, url=https://system-image.ubports.com//ubports-touch/16.04/rc/frieza/version-6.tar.xz, path=/home/udoo/.cache/ubports/pool, checksum=2242da23ce34d6b0c6793852bacb7a4923cccf3fea7932981296d79d452c1d6c, url=https://system-image.ubports.com//ubports-touch/16.04/rc/frieza/version-6.tar.xz.asc, path=/home/udoo/.cache/ubports/pool, url=https://system-image.ubports.com/gpg/image-signing.tar.xz, path=/home/udoo/.cache/ubports/gpg, url=https://system-image.ubports.com/gpg/image-signing.tar.xz.asc, path=/home/udoo/.cache/ubports/gpg, url=https://system-image.ubports.com/gpg/image-master.tar.xz, path=/home/udoo/.cache/ubports/gpg, url=https://system-image.ubports.com/gpg/image-master.tar.xz.asc, path=/home/udoo/.cache/ubports/gpg
    error: Not existing /home/udoo/.cache/ubports/pool/ubports-074647d5912a2423537abc8874438dc53d59a5a6b7887cb02eac0f6a28ef7169.tar.xz
    error: Not existing /home/udoo/.cache/ubports/pool/ubports-074647d5912a2423537abc8874438dc53d59a5a6b7887cb02eac0f6a28ef7169.tar.xz.asc
    error: Not existing /home/udoo/.cache/ubports/pool/device-2ca0785269f85a0f7480633ad9adbe72f8b4020df6a10657eb23cd6abe601481.tar.xz
    error: Not existing /home/udoo/.cache/ubports/pool/device-2ca0785269f85a0f7480633ad9adbe72f8b4020df6a10657eb23cd6abe601481.tar.xz.asc
    info: checked: keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
    info: /home/udoo/.cache/ubports/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz already exists with the expected checksum, so download will be skipped
    info: /home/udoo/.cache/ubports/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc already exists with the expected checksum, so download will be skipped
    error: Not existing /home/udoo/.cache/ubports/pool/version-6.tar.xz
    error: Not existing /home/udoo/.cache/ubports/pool/version-6.tar.xz.asc
    info: /home/udoo/.cache/ubports/gpg/image-signing.tar.xz already exists with the expected checksum, so download will be skipped
    info: /home/udoo/.cache/ubports/gpg/image-signing.tar.xz.asc already exists with the expected checksum, so download will be skipped
    info: /home/udoo/.cache/ubports/gpg/image-master.tar.xz already exists with the expected checksum, so download will be skipped 
    info: /home/udoo/.cache/ubports/gpg/image-master.tar.xz.asc already exists with the expected checksum, so download will be skipped
    info: Starting download of 6 files
    info: Downloading file, 1% complete
        [...]
    info: Downloading file, 100% complete
    info: Download checking file
    info: checked: ubports-074647d5912a2423537abc8874438dc53d59a5a6b7887cb02eac0f6a28ef7169.tar.xz
    error: Devices: Download error Checksum did not match on file ubports-074647d5912a2423537abc8874438dc53d59a5a6b7887cb02eac0f6a28ef7169.tar.xz

The device used to have Android on it and was freshly flashed via the bq/mediatek SP-flash-tool and the  **frieza-image-stable-8.zip**  which left me with a working ubuntu touch last updated 07.02.2017.

How can I proceed? Thank you.

**Comment by uududde** [comment]
partly solved... thanks to the info here:  #384 see: [#issuecomment-407912873](https://github.com/ubports/ubports-installer/issues/384#issuecomment-407912873)

I had also seen this error 
    Uncaught Error: EACCES: permission denied, open '/home/...
before. So I uninstalled the snap and the deb and also deleted the ~/.cache/ubports/ folder. Then I installed the release ubports-installer_0.1.11-beta_amd64.deb.

I then flashed the 15.04/stable which worked. I am now on ubports 15.04 (r3)  from the 03.01.18.

I guess I can now flash to 16.04/rc so will give it a try right away.

**Comment by uududde** [comment]
something did not go well... ubports-installer worked its way through and finished saying 'success!' 
m10 was still in fastboot mode with a little yellow message saying "installing ubuntu touch" (or something like that)... I left it like that for half an hour (since ubports said it might take 5 min) but then lost it and rebooted via the fastboot "reboot the device"... and ended up back with still having 15.04 (r3)

**Comment by uududde** [comment]
restarted the ubports-installer and this time it went through again with 'success!' and there was more going on after flashing/pushing file 3. First time it was as if after file 3 it didn't continue to push other files... this time you could see a very fast pushing of the files up to number 13. After flashing the m10 restarted and the ubuntu circle was turning for around 5 min after which ubuntu started and now I am on 16.04 (2018-W30)... wonderful!
