### ISSUE TITLE
ubports-installer cannot flash newly purchased Nexus 5

### ISSUE THREAD

**Issue by kurji** [ubports/ubports-installer#95]
I just bought a Nexus 5 specifically with the intent of loading Ubuntu Touch on it. I haven't done anything to the phone except enable Developer Mode and USB debugging.

On both my Windows 7 machine and my Linux Mint machine, the UBports installer stops at the "Please reboot to bootloater" screen and cannot continue, even though the phone is plugged in and I followed the instructions to reboot to the bootloader.

On Linux, my issue is similar to #88 except that running `ubports-installer` with `sudo` didn't fix anything.

Logs from running `sudo ubports-installer`:

```
debug: Using fallback platform tools!
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb kill-server
debug: 
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 kill-server
debug: 
debug: Running platform tool fallback exec asar cmd [object Object] -P 5038 start-server
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
* daemon not running; starting now at tcp:5038
* daemon started successfully
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
debug: adb shell: echo 1
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 shell echo 1
debug:  Error: Command failed: /tmp/.org.chromium.Chromium.qGh0Ab -P 5038 shell echo 1
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

At this point, I progressed to the "Please reboot to bootloater" screen:

```
debug: fastboot: wait for device
debug: Running platform tool fallback exec asar cmd fastboot devices
debug: Running platform tool fallback exec asar cmd fastboot devices
debug: Running platform tool fallback exec asar cmd fastboot devices
debug: Running platform tool fallback exec asar cmd fastboot devices
debug: Running platform tool fallback exec asar cmd fastboot devices
debug: Running platform tool fallback exec asar cmd fastboot devices
debug: Running platform tool fallback exec asar cmd fastboot devices
```

At this point, I closed the application:

```
plat
{ fallback: 
   { fastboot: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/fastboot',
     adb: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/adb' } }
debug: Using fallback platform tools!
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb kill-server
Good bye!
debug: 
plat
{ fallback: 
   { fastboot: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/fastboot',
     adb: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/adb' } }
debug: Running platform tool fallback exec cmd /opt/ubports-installer/resources/app.asar/platform-tools/linux/adb -P 5038 kill-server
debug:  Error: ENOENT, platform-tools/linux/adb not found in /opt/ubports-installer/resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:215:16)
    at Object.platfromToolsExec (/opt/ubports-installer/resources/app.asar/src/utils.js:228:8)
    at utils.platfromToolsExec (/opt/ubports-installer/resources/app.asar/src/adb.js:49:13)
    at /opt/ubports-installer/resources/app.asar/src/utils.js:208:5
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
undefined
false
```

![screenshot from 2018-02-17 17 38 14](https://user-images.githubusercontent.com/22146019/36572095-9cdeb0b0-1885-11e8-82e9-78b026e73ce4.png)
![screenshot from 2018-02-17 17 40 22](https://user-images.githubusercontent.com/22146019/36572096-9d1bad94-1885-11e8-9380-39200fe12b97.png)
![screenshot from 2018-02-17 17 43 32](https://user-images.githubusercontent.com/22146019/36572094-9ca4d926-1885-11e8-9315-1e82bf0f5009.png)

Could this be related to #94?

**Comment by NeoTheThird** [comment]
On windows, you'll have to install adb drivers manually (#12), [this one](https://adb.clockworkmod.com/) should work. On linux that should not be necessary.

It can happen, that the installer looses the connection to the device during installation, especially when using cheap or old usb cables. Please try again with the latest version of the installer (a new release will be published later tonight). Try multiple times with different usb cables and ports, if possible. To confirm that your device is in fact in bootloader mode, you can also open a new terminal window (on linux) and run `sudo fastboot devices`, that should output one line containing an alphanumeric string and the word fastboot. If you do not see any output, your device is not in fastboot mode, or the computer does not recognize it. To make sure the device is actually in fastboot mode, look at the devices screen. The nexus 5 has a very recognizable fastboot screen that should look like this:
![nexus 5 fastboot screen](https://i.ytimg.com/vi/mHJV_UprpE8/maxresdefault.jpg)

**Comment by kurji** [comment]
Thank you for your help. The latest version of the installer worked, after multiple tries with various USB cables. I suggest making more useful error messages that indicate when the process has stopped due to a disconnection, with (a link to) some of these debugging tips, as the process stopped itself multiple times and required me to redo everything each time.

**Comment by NeoTheThird** [comment]
Good to hear it worked. Yes, we still have some stuff to do there, thanks for your feedback
